### ISSUE TITLE
MRTK GA Release Progress

### ISSUE THREAD

**Issue by AMollis** [MixedRealityToolkit/MixedRealityToolkit-Unity#16]
# Overview
Here's the current timeline for the MRTK3 GA

- [x] Aug 21 - Microsoft announces new organization 
- [x] Aug 21 - Make new repository public
- [x] Aug 21 - Pre-release MRTK3 preview 18
- [x] Sep 6-13 - Release MRTK3 GA via Microsoft's NPM feed using org.mixedrealitytoolkit.* packages

# Details

<html>
<body>
<div fluid-config-type="Tabular"><div></div>

Start Date | End Date | Task | Owner | Progress
-- | -- | -- | -- | --
Fri, Aug 11 | Fri, Aug 11 | Create "releases/3.0.0-pre.18” branch in new repository. | @shaynie | Completed
Fri, Aug 11 | Fri, Aug 11 | Create preview packages for 3.0.0-pre.18 | @shaynie | Completed
Fri, Aug 11 | Fri, Aug 11 | Final reviews with writers about new MRTK Org announcement. | @kevincol |Completed
Mon, Aug 14 | Tue, Aug 22 | Microsoft validates 3.0.0-pre.18 preview packages | Microsoft | Completed
Wed, Aug 21 | Wed, Aug 21 | Microsoft announces new MRTK Organization. Microsoft posts an announcement on the Microsoft Tech site. | Kevin Collins | Completed
Wed, Aug 21 | Wed, Aug 21 | Publish MRTK 3.0.0-pre.18 packages to NPM feed (and MRFT), and project's [releases page](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/releases). | Microsoft | Completed
Wed, Aug 21 | Wed, Aug 21 | Publish MRTK 3.0.0-pre.18 release notes | Microsoft | Completed
Wed, Aug 21 | Wed, Aug 21 | Create "releases/3.0.0” branch in new repository. | @shaynie | Completed
Tue, Sep 6 | Tue, Sep 13 | Create final GA package for 3.0.0 | @shaynie | Completed
Wed, Sep 6 | Wed, Sep 13 | Publish MRTK 3.0.0 (GA) packages to NPM feed (and MRFT), and project's [releases page](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/releases). This includes packages and release notes. | Microsoft | Completed
Wed, Sep 6 | Wed, Sep 13 | Publish MRTK 3.0.0 (GA) release notes | Microsoft | Completed
Wed, Sep 6 | Thu, Sep 13 | Publish MRTK3 API Reference Docs | Microsoft | Completed

</div>
</body>
</html>

**Comment by shaynie** [comment]
Also completed and published learning paths
