### ISSUE TITLE
MRTK3 Audio spatializers support MS Spatializer x86-64 for ML

### ISSUE THREAD

**Issue by AMollis** [MixedRealityToolkit/MixedRealityToolkit-Unity#27]
# Overview

Investigate ways to improve Audio Spatializer support in MRTK3.  

# Additional Context

Sounds like there are issues relying on the MSFT Spatializer on other devices, like Magic Leap.

**Comment by shaynie** [comment]
@david-c-kline will add documentation around this

**Comment by shaynie** [comment]
Can MS compile x86 android version of Microsoft Spatializer?  
Probably not.
Msft to investigate
Msft to get link to source

**Comment by AMollis** [comment]
@ghazen-ml , has Magic Leap investigated build the x86 Android version of this plugin?

https://github.com/microsoft/spatialaudio-unity

**Comment by shaynie** [comment]
The component needed to make this work is closed source and probably not updatable in the near term.
