### ISSUE TITLE
Update code owners file

### ISSUE THREAD

**Issue by david-c-kline** [MixedRealityToolkit/MixedRealityToolkit-Unity#33]
Current code owners list does not include non-MSFT maintainers.

**Comment by shaynie** [comment]
@david-c-kline Not limited to maintainers.  Additional people can be added as needed.

**Comment by AMollis** [comment]
@david-c-kline , can we close this issue?

**Comment by AMollis** [comment]
closing this, as I believe this is done.  @david-c-kline , re-opened as needed.
