### ISSUE TITLE
[BUG] Slider Max Value Field causes slider to extend past the visual bounds

### ISSUE THREAD

**Issue by Alzaro** [MixedRealityToolkit/MixedRealityToolkit-Unity#442]
## Describe the bug

The slider component starts with a min value of 0 and a Max Value of 1. The slider will work as expected until you change the Max Value to something more than 1.

## To reproduce

1. Open a new scene in Unity that contains the CanvasSlider prefab from MRTK
2. Change the Max Value on the Slider component to 10
3. Press play in Unity
4. Drag the slider 
5. Observe that you can drag the slider past the visual indicators (even off of your canvas object)

## Expected behavior

I would expect the Max Value to just change the values of the slider from 0-MaxValue without it going past the visual bounds.
It should act the same as going from 0-1.

## Screenshots

Slider showing the bounds of the object.
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/16711165/dad603c4-af70-48e2-9987-de8531dbb3fa)

Slider showing that you can go PAST the bounds
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/16711165/d3b7b020-8360-498e-bcec-b777ec71ea41)

## Your setup (please complete the following information)

- Unity Version 2022.3.4
- MRTK3 - 1.0.5

## Target platform (please complete the following information)

- Magic Leap

**Comment by shaynie** [comment]
@Alzaro Hi, thanks for logging the bug.  This bug was fixed in the old repo as part of this pull request:  https://github.com/microsoft/MixedRealityToolkit-Unity/pull/11742

I verified that the version here in the new repo contains the fix.  Please update and report back if you still have problems.
Thanks!
