### ISSUE TITLE
[BUG] MRTK URP support for Unity 2021 (URP 12.1.12+)

### ISSUE THREAD

**Issue by paulio** [MixedRealityToolkit/MixedRealityToolkit-Unity#449]
## MRTK URP support for Unity 2021 (URP 12.1.12+)

Installing MRTK in a Unity 2021 project that is using URP incorrectly produces invisible materials. When the MRTK Standard opaque shader is applied the material is incorrectly invisible. The problem is not seen in Unity 2020 projects. The problem occurs for both MRTK v2 and v3. 

## To reproduce

1. Create an Unity 2021 project using the URP (3D) Template
2. Using the MRTK feature tool add the standard set of assets and the Shader examples. 
3. Use the MRTK Upgrade URP Materials tool menu (if using v2)
4. Once the install is complete view the Shader Material examples or create a new opaque material using the MRTK Standard shader
5. Note that you cannot see the resulting material in either the preview or when the material is applied to a mesh (e.g. a simple cube)

## Expected behavior

The Shader should display the color as stipulated in the shader settings

## Screenshots
Expected (from Unity 2020)
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/235897/0dc34fa9-2d95-4f2b-afd5-86a55fdaf845)

Unity 2021
MRTK 2
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/235897/6539f5be-7860-4666-b813-965cca0402b8)

MRTK 3
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/235897/a9496117-920a-4665-a391-acba537da31b)

## Your setup (please complete the following information)

- Unity Versions
2021.3.29f1
2020.3.42 (used to produce the working examples)
- MRTK Version 
MRTK2 2.8.3
MRKT3 3.0.0-pre18

## Target platform (please complete the following information)

- HoloLens 2

**Comment by AMollis** [comment]
@paulio  can you please open this bug against the Mixed Reality Graphics Tools. 

https://github.com/microsoft/MixedReality-GraphicsTools-Unity

This Graphic Tools is currently a stand-alone project still maintained by the Microsoft organization.

**Comment by paulio** [comment]
Thanks, FYI [https://github.com/microsoft/MixedReality-GraphicsTools-Unity/issues/189](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/issues/189)
