### ISSUE TITLE
[FEATURE REQUEST] public preview release versioning (e.g 3.0.1-preview)

### ISSUE THREAD

**Issue by ghazen-ml** [MixedRealityToolkit/MixedRealityToolkit-Unity#459]
# Overview

We need to update the build pipeline to handle "public preview" release.    For example, a preview of a patched version of `org.mixedrealitytoolkit.input` should be versioned as 3.0.1-preview.  From what I understand the pipeline doesn't handle this.

# Additional Information

Context: https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/458

**Comment by AMollis** [comment]
I had asked for this to be open.


We also should document guidelines on when a preview version is needed, and how (or if) we handle iterations of preview versions.

**Comment by shaynie** [comment]
@shaynie Build hash table of preview versions in settings.yaml

**Comment by shaynie** [comment]
Proposed change:  Any functionality change that forces a minor or major version change needs a preview release.  Maintainers to decide how long each preview should exist in the wild before a full release.

**Comment by AMollis** [comment]
We want to make the -pre.x tag a per package thing.

**Comment by AMollis** [comment]
Each package can specify its own public preview meta tag and version.   We will continue to use the "-pre.#" labeling.  For example, `org.mixedrealitytoolkit.data-pre.20`.   

See the following PR for details

- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/777
