### ISSUE TITLE
[BUG] Dictation Subsystem not responding after some attempts

### ISSUE THREAD

**Issue by ragavendranbalaCES** [MixedRealityToolkit/MixedRealityToolkit-Unity#463]
## Dictation Subsystem not responding after some attempts

I have created a speech to text feature on the HoloLens 2 with Dictation subsystem, it failed to detect the voice after few attempts. 

## To reproduce

1. Implement Dictation feature on the project and install the app on HoloLens 2
2. Start and stop dictation with button click frequently
3. The App will stop the dictation but won't show any errors.

## Expected behavior

The Dictation should work every time.

- Unity Version 2020.3.33f1
- MRTK Version 3.0.0-pre.14
- MRTK Window Text to Speech Plugin 1.0.1

## Target platform

- HoloLens 2

**Comment by shaynie** [comment]
@ragavendranbalaCES Thank you for submitting the bug.  Do you see the same behavior in the current "DictationExample" scene?

**Comment by AMollis** [comment]
@ragavendranbalaCES if you are also using the keyword recognizer (i.e. saying "Select" to click a button), you'll have to first disable the keyword recognizer.   You can find a sample of this in the DictationExample that @shaynie motioned.   Here's the code:

https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/blob/da13aa84f7f8a99e741d7e8c25196721397ea6ce/UnityProjects/MRTKDevTemplate/Assets/Scripts/DictationHandler.cs#L64C13-L69C1

```
                keywordRecognitionSubsystem = XRSubsystemHelpers.KeywordRecognitionSubsystem;
                if (keywordRecognitionSubsystem != null)
                {
                    keywordRecognitionSubsystem.Stop();
                }

```

**Comment by ragavendranbalaCES** [comment]
Hi @shaynie , my code is the modified version of DictationHandler.cs file which is used in Dictation Example scene

**Comment by ragavendranbalaCES** [comment]
Hi @AMollis , the MRTK version which I'm using doesn't having the methods Stop() for keyword recognition subsystem.

**Comment by shaynie** [comment]
@ragavendranbalaCES, Please upgrade to the official 3.0.0 toolkit release.  Every subsystem has a Stop() method, so you'll need to follow @AMollis's suggestion and stop the KeywordRecognitionSystem before enabling dictation.  Re-open the bug if you retest with the released toolkit and it is still causing you problems.
