### ISSUE TITLE
Document how critical bugs should be resolved and released

### ISSUE THREAD

**Issue by AMollis** [MixedRealityToolkit/MixedRealityToolkit-Unity#466]
## Describe the issue

In the unlikely event of a critical bug, what process should the Project Maintainers follow to address the issue in a timely manner?  We should have clear guidelines outlining the escalation process for Project Maintainers.  

## Feature area

Project Management

## Existing doc link

It probably makes sense to append this documentation with the critical bug process.

https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/blob/main/contributions/versioning-and-releases.md

**Comment by shaynie** [comment]
@shaynie  or @AMollis  to send emergency email to discuss with maintainers when critical bugs arise.  @AMollis to set up mail group.
