### ISSUE TITLE
[BUG] Cannot load MRTK3 GA in Unity 2021.3.16f1 .... Update min Unity versions in package manifest files

### ISSUE THREAD

**Issue by david-c-kline** [MixedRealityToolkit/MixedRealityToolkit-Unity#467]
## Describe the bug

I have a client who is using Unity 2021.3.16f1 and is unable to load the GA release due to the following:

- Library\PackageCache\org.mixedrealitytoolkit.core@e0a4c2c13eef\Utilities\ComponentCache.cs(38,45): error CS0117: 'Object' does not contain a definition for 'FindFirstObjectByType'
- Library\PackageCache\org.mixedrealitytoolkit.core@e0a4c2c13eef\Utilities\ControllerLookup.cs(64,17): error CS0103: The name 'FindObjectsByType' does not exist in the current context
- Library\PackageCache\org.mixedrealitytoolkit.core@e0a4c2c13eef\Utilities\ControllerLookup.cs(64,53): error CS0103: The name 'FindObjectsSortMode' does not exist in the current context

These calls appear to have been added after pre.17.

Unfortunately, the Unity documentation does not detail in which specific revision these APIs were added. I can confirm that the GA core package does load in 2021.3.30f1.

## To reproduce

1. Install Unity 2021.3.16f1
2. Import org.mixedrealitytoolkit,.core GA
3. Observe errors

## Expected behavior

Packages to be tagged with their true minimum requirements (Unity version and revision)

## Your setup (please complete the following information)

- Unity Version 2021.316f1
- MRTK3 GA (org.mixedrealitytoolkit.core 3.0.0)

## Target platform (please complete the following information)

- All platforms

**Comment by david-c-kline** [comment]
From looking through each of Unity's 2021.3 revision release notes, it appears that MRTK3 GA requires [2021.3.18f1](https://unity.com/releases/editor/whats-new/2021.3.18).

- Scripting: Added: New Object.FindFirstObjectByType() and Object.FindAnyObjectByType() functions added as potentially faster alternatives to Object.FindObjectOfType(). These new functions let you decide whether you must have the first (lowest InstanceID) object found or if any instance is adequate. In the latter case the function can be many times faster as no internal sorting is required. See the scripting documentation for both functions for more details.

- Scripting: Added: New Object.FindObjectsByType() function added as a potentially faster alternative to Object.FindObjectsOfType(). This new function gives users the choice whether or not to perform the expensive sorting by InstanceID on the returned collection of objects rather than having it always performed wasting time when unnecessary. See the scripting documentation for Object.FindObjectsByType() and Object.FindObjectsOfType() for more details.

I will continue to look and see if there have been any more API changes since  revision 18f1

**Comment by shaynie** [comment]
@david-c-kline Thanks for the bug.  Our minimum version is actually 2021.3.22f1.  See https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/blob/main/README.md#requirements

**Comment by shaynie** [comment]
@david-c-kline I'm reopening this bug to remind us to update the manifest to prevent installation on Unity versions < 2021.3.22

**Comment by shaynie** [comment]
@david-c-kline is working on updating the manifests for the packages to require 2021.3.22+

**Comment by AMollis** [comment]
We should #ifdef these new APIs so they work in .16

**Comment by AMollis** [comment]
Fixed with change this change

- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/commit/bef0816936e10db8b652952a999640e634620d35

**Comment by ghazen-ml** [comment]
Per the following release notes page it appears that these apis may have been added in 2022.2.5 too?: https://unity.com/releases/editor/whats-new/2022.2.5#release-notes (so it wasn't in all 2022 versions)

I found that 2022.2.2.f1 actually didn't have this api even though it is >= 2021.3.18
