### ISSUE TITLE
[FEATURE REQUEST] Make CI or nightly builds available to public feed

### ISSUE THREAD

**Issue by AMollis** [MixedRealityToolkit/MixedRealityToolkit-Unity#476]
## Overview

Developers may want to test nightly builds of the MRTK3 packages.  We currently have CI builds published to a private feed, we should consider making these or nightly CI "roll-up" builds available to developers.

Without this, developers have to use the GitHub project directly

**Comment by shaynie** [comment]
With the plan to release from the unity store this doesn't make sense anymore.
