### ISSUE TITLE
🚀 Package Update - UX Components (Non-Canvas) v3.1.0

### ISSUE THREAD

**Issue by AMollis** [MixedRealityToolkit/MixedRealityToolkit-Unity#486]
Ship package update for UX Components  (Non-Canvas) v3.1.0

Fixes to include:

- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/493
- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/438

**Comment by shaynie** [comment]
Update package version of UX Components to 3.1.0 with this change.
