### ISSUE TITLE
🚀 Package Update - UX Core v3.1.0

### ISSUE THREAD

**Issue by AMollis** [MixedRealityToolkit/MixedRealityToolkit-Unity#487]
Ship package update for UX Core v 3.1.0

Fixes to include

- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/472
- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/438
- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/435

**Comment by shaynie** [comment]
@shaynie, @david-c-kline  Verify that the UX Components package version gets updated to 3.1.0
