### ISSUE TITLE
[BUG] Unity + MRTK3 + Hololens 2 Low Framerate

### ISSUE THREAD

**Issue by FelixLenainInod** [MixedRealityToolkit/MixedRealityToolkit-Unity#489]
## Describe the bug

I just created a simple Unity project just to check MRTK3 performances, once build and running on Hololens 2 a simple scene containing a slate and a cube to manipulate runs at 20 FPS.
So i tried the sample scenes provided on the [github ](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity) and once build, scenes are running at 15 fps.
I did follow all MRTK's and Unity advice to optimize the performances, but I should be missing something somewhere...

## To reproduce

1. Clone Github Scene Examples (MRTKDevTemplate)
2. Run Unity project using 2021.3.21 LTS version
3. Build project with VS 2022
4. Run on up to date Hololens 2

## Expected behavior

In order to provide users a nice experience, simple scenes should run close to 60 FPS.

## Your setup (please complete the following information)

- Unity Version 2021.3.21f1
- MRTK v3.0.0 GA

## Target platform (please complete the following information)

- HoloLens 2

**Comment by AMollis** [comment]
@FelixLenainInod please verify that all the mesh renderers are using the Shaders from MRTK's Graphics Toolkit.

Also, what flavor of the project are you building Debug, Release, or Master?

Also, can you have changed any of the sample project settings?  Please provide the project settings you are using.

Note, we cannot reproduce this issue.

**Comment by shaynie** [comment]
@FelixLenainInod Are you using the built in render pipeline?

**Comment by FelixLenainInod** [comment]
Hi guys,

@AMollis Thanks for the advices, my mistake was to build in Debug mode after building in Master mode the performances are here, 60 FPS with no problem. Thank you

@shaynie Yes i'm using the Built-in pipeline.
