### ISSUE TITLE
[BUG] Unable to build Appx by cloning the repo

### ISSUE THREAD

**Issue by ragavendranbala** [MixedRealityToolkit/MixedRealityToolkit-Unity#496]
## Describe the bug
Tried to cloning the repo and built the solution for HL2 and no option for Publishing the App

## To reproduce

1. Clone the main branch 
2. Open it on Unity (Project is on Unity 2021.3 so I used latest version of 2021.3)
3. Switch to UWP, Select arch as "ARM 64-bit"
4. Enable Holographic under suported device families in Project settings.
5. Build the project
6. Open the solution in VS 2022
7. Try to build appx from the solution.

## Expected behavior

It should show the publish option to build the APPX.

## Screenshots

![Unity_CzRL8kP2pR](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/32410475/0d8db5d6-d5a2-40b1-9d48-188bfe371418)
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/32410475/549e52fc-5e6b-43b0-b82e-f794429eedd0)

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/32410475/0f1ab59b-70c0-465e-bc0c-56e0770fc3e6)
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/32410475/e4a13ad5-ee19-480d-8542-8812360f2899)
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/32410475/d9a582dd-4a68-4f44-ae12-868d19b98998)

## Your setup (please complete the following information)

- Unity Version 2021.3.30f1
- MRTK Version or Commit https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/commit/125e8add28d5837150e0a177483a346a3999a486

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

Publish option is showing on the project built with Unity 2022.3
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/32410475/61a4f706-0a0b-4a0a-bc96-f6bc0d685135)

**Comment by AMollis** [comment]
@ragavendranbala   Unity is not adding the AppxManifest item to the cvxproj file.

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/36461279/55c6bdd2-34af-4f85-bfe8-72fa08b4046a)

If you manually add this, appx packaging will work again.

**Comment by AMollis** [comment]
@ragavendranbala is aware of this issue.  Please status of this bug at these locations:

1. https://forum.unity.com/threads/unity-version-2021-3-28f1-lacks-the-uwp-publish-button-in-visual-studio-build-for-package-generation.1480761/
2. https://issuetracker.unity3d.com/issues/create-app-packages-dot-dot-dot-option-is-greyed-out-when-trying-to-create-app-packages-in-visual-studio  

This should be fixed in 2021.3.31  

Thank you for reporting this issue.  Resolving this issue as external
