### ISSUE TITLE
[BUG] Add More IfDefs To Get Rid of Warnings in 2023

### ISSUE THREAD

**Issue by marlenaklein-msft** [MixedRealityToolkit/MixedRealityToolkit-Unity#502]
## Describe the bug

In 2023, there are a ton of warnings about various deprecated FindObject functions. Need to replace with the more efficient new versions, similar to this https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/484.

## Screenshots
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/125413876/e554cdc0-98ba-41d9-a3c0-ab9c8f81695d)

## Your setup (please complete the following information)

- Unity 2023.2

**Comment by AMollis** [comment]
We should fix this :)

**Comment by AMollis** [comment]
@marlenaklein-msft please add the "package: *" labels for all impacted packages.

**Comment by marlenaklein-msft** [comment]
Added. (mostly these are unit tests)
