### ISSUE TITLE
[BUG] MRTK Example Project Aquarium crashes to Shell Environment on Launch

### ISSUE THREAD

**Issue by ARGs-code** [MixedRealityToolkit/MixedRealityToolkit-Unity#513]
## Describe the bug

Entire project doesn't seem to be functional on Hololens 2. There is not much useful information in the Unity Log before it abruptly ends.

## To reproduce

Follow the documentation here: https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/mrtk3-aquarium
Clone the repo listed in the documentation: https://github.com/microsoft/MRTK3-iet-tutorials
Open in Unity 2021.3.28f1
Target UWP, ARM64 Architecture.
Change player settings so platform target Holographic is checked.
Open and Run Aquarium scene in the Editor. Everything appears to work as intended.
Add Aquarium scene to build (it's the only scene in the build).
Build project.
Open Visual Studio SLN from Unity build. Target ARM64, Release. Build and deploy.
Open App on Hololens 2.
App Crashes to Shell Environment before anything else happens.

## Expected behavior

Project functions in Hololens 2 like it functions in the Unity Editor.

## Your setup (please complete the following information)

- Unity Version 2021.3.28f1

## Target platform (please complete the following information)

- HoloLens 2
- OpenXR

## Additional context

Included the Unity Log that results, though there isn't a lot of helpful info there.
[ExampleMRTK3Issue.log](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/files/12884228/ExampleMRTK3Issue.log)

**Comment by AMollis** [comment]
Hi @ARGs-code  what version of "com.unity.inputsystem" are you using?   An older version of  "com.unity.inputsystem" will crash on launch.   Please update "com.unity.inputsystem" to 1.6.1 and try again.

We should also update this sample to latest MRTK3

**Comment by ARGs-code** [comment]
Thanks for the quick response @AMollis .

I'm not sure if it was the 1.6.1 or changing the .net to .net framework from .net 2.1 but things are working now as expected.

The project by default was on the .net 2.1 framework.
