### ISSUE TITLE
[BUG] [EDITOR] Some menu "GameObject -> UI -> MTRK" don't work if no main camera loaded

### ISSUE THREAD

**Issue by anonymous2585** [MixedRealityToolkit/MixedRealityToolkit-Unity#520]
## Describe the bug

Our project has a root scene that load different scene depending on a custom profile.
The root scene doesn't has any camera. The main camera is in another scene loaded at startup.

When designing UI, the sortcuts `GameObject -> UI -> MTRK -> Canvas + Graphics Raycasting` and `GameObject -> UI -> MTRK -> Canvas` don't work, because the script tries to place the new canvas face to the main camera.

When editing a prefab, the sortcuts `GameObject -> UI -> MTRK -> Canvas + Graphics Raycasting` and `GameObject -> UI -> MTRK -> Canvas` place the new canvas in the active scene, not in the actual prefab being edited.

## To reproduce

1. Create and load a scene with no camera
2. Use the menu `GameObject -> UI -> MTRK -> Canvas + Graphics Raycasting` or `GameObject -> UI -> MTRK -> Canvas`
3. See error, and an incomplete canvas created

```
NullReferenceException: Object reference not set to an instance of an object
MixedReality.Toolkit.Editor.CreateElementMenus.SetReasonableCanvasDefaults (UnityEngine.Canvas canvas) (at ./Library/PackageCache/org.mixedrealitytoolkit.uxcomponents@58744f787171/Editor/CreateElementMenus.cs:108)
MixedReality.Toolkit.Editor.CreateElementMenus.CreateGraphicRaycastingCanvas (UnityEditor.MenuCommand menuCommand) (at ./Library/PackageCache/org.mixedrealitytoolkit.uxcomponents@58744f787171/Editor/CreateElementMenus.cs:149)
```

## Expected behavior

The requested canvas is created at the origin.

## Your setup (please complete the following information)

- Unity Version: 2023.1.16f1
- MRTK UX Components 3.1.0

**Comment by AMollis** [comment]
We should investigate fixing this

**Comment by shaynie** [comment]
In PR.  #527
