### ISSUE TITLE
[BUG] Slider handle not correcly set when value set by script

### ISSUE THREAD

**Issue by anonymous2585** [MixedRealityToolkit/MixedRealityToolkit-Unity#523]
## Describe the bug

I have two sliders that misbehave in my project.

Sliders goes from 0 to 3 with a default value of 1 and are desactivated by default in the scene. I have a call to `slider.Value = 2.5f` during the same frame as the `gameObject.SetActive(true)`. Sliders are children of multiples canvas layouts.
The fill background is correctly set, but not the handle;

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/148471165/0746015e-f0d3-4969-8f11-c733a2432885)

I added some logs, the issue comes from the Slider `TrackDirection` that is no corrrect when my script call `slider.Value = x`.

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/148471165/46be27b4-1e4d-45fb-923a-514c4a6a1655)
Logs 1 to 3 are from the MRTK initializing (multiple times) the slider.
The 4th logs comes from my script triggering `slider.Value = 2.5f`, handle is incorrectly placed.
The 5th logs come from a mouse click on the slider at the fill end position. The handle is then correcly placed.

As you can see, `TrackDirection` is incorrect during the 4 first logs.

The problem comes from this line:
https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/blob/e30b350c131501084a4f9003cba1361248717f66/org.mixedrealitytoolkit.uxcore/Slider/Visuals/CanvasSliderVisuals.cs#L202C18-L202C18

Is it possible to do the computation "in canvas space" with anchors (like the `fillVisual`) instead of setting the absolute world position?

## Expected behavior

The handle is set at the same place than the fill ends.

## Your setup (please complete the following information)

- Unity Version 2023.1.16f1
- MRTK UX Components 3.1.0

**Comment by anonymous2585** [comment]
@marlenaklein-msft
If you replace the `UpdateHandle` function with this, it solves the issue for me.

```c#
        // Update the things that depend on the slider value.
        void UpdateHandle(float value)
        {
            switch (SliderDirection)
            {
                case Direction.LeftToRight:
                    fillVisual.anchorMax = new Vector2(value, 1.0f);
                    handle.anchorMin = new Vector2(value, handle.anchorMin.y);
                    handle.anchorMax = new Vector2(value, handle.anchorMax.y);
                    break;
                case Direction.RightToLeft:
                    fillVisual.anchorMin = new Vector2(1.0f - value, 0.0f);
                    handle.anchorMin = new Vector2(1.0f - value, handle.anchorMin.y);
                    handle.anchorMax = new Vector2(1.0f - value, handle.anchorMax.y);
                    break;
                case Direction.BottomToTop:
                    fillVisual.anchorMax = new Vector2(1.0f, value);
                    handle.anchorMin = new Vector2(handle.anchorMin.x, value);
                    handle.anchorMax = new Vector2(handle.anchorMax.x, value);
                    break;
                case Direction.TopToBottom:
                    fillVisual.anchorMin = new Vector2(0.0f, 1.0f - value);
                    handle.anchorMin = new Vector2(handle.anchorMin.x, 1.0f - value);
                    handle.anchorMax = new Vector2(handle.anchorMax.x, 1.0f - value);
                    break;
            }
            handle.anchoredPosition = Vector3.zero;
        }
```

I let you check if it's correct for other orientations than `Direction.LeftToRight` (I didn't test) and other use cases.

**Comment by anonymous2585** [comment]
Will I'm on the canvas slider, I noticed that in the prefab `CanvasSlider`, the GameObject `End` has an arbirary width of `617.13`. (It's bigger than the parent width of 100).

Can you set the default `End` width to 0 in the prefab?

**Comment by marlenaklein-msft** [comment]
Hi @anonymous2585, thanks for logging this and your workaround!

When adding a test script to change the value of the slider programmatically, I have not observed this issue with the handle placement. Would you be able to post the project you are working in or a set of general steps to repro the issue?

**Comment by anonymous2585** [comment]
Hi,
Here is the repro steps:
1. Import this Unity package in the project of this repo [CanvasSliderBug.zip](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/files/13296988/CanvasSliderBug.zip)
2. Open the scene `CanvasSliderBug`
3. Press play an see the bug

I already spent too much time on this simple issue: don't use absolute world position for UI elements!

**Comment by marlenaklein-msft** [comment]
Thanks for providing this, I have been able to repro the issue and the fix. We'll make the change! https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/549
