### ISSUE TITLE
[FEATURE REQUEST] unreal version

### ISSUE THREAD

**Issue by peterclemenko** [MixedRealityToolkit/MixedRealityToolkit-Unity#528]
could you please transition the unreal engine version to this and get it back in the epic launcher working with the latest engine versions?

**Comment by AMollis** [comment]
Unfortunately, we are not looking to support Unreal at this time

**Comment by peterclemenko** [comment]
Understood, please reconsider when you have the resources, being able to use mrtk, even if the existing one out of the box in unreal would be a great thing.
