### ISSUE TITLE
Remove obsolete methods (with XRI 3.0 Updates)

### ISSUE THREAD

**Issue by david-c-kline** [MixedRealityToolkit/MixedRealityToolkit-Unity#531]
It was originally intended that obsolete methods be removed prior to GA. Unfortunately, a few packages still have methods that should not be used.

NOTE: Removing these methods will require a _major_ version update for each impacted package.

> org.mixedrealitytoolkit.core\Utilities\Extensions\HandednessExtensions.cs:44:        [Obsolete("Use flags instead (e.g. Handedness.Right | Handedness.Left)")]
org.mixedrealitytoolkit.core\Utilities\Extensions\HandednessExtensions.cs:56:        [Obsolete("Use flags instead (e.g. Handedness.Right | Handedness.Left)")]
org.mixedrealitytoolkit.core\Utilities\Extensions\HandednessExtensions.cs:68:        [Obsolete("Use flags instead (e.g. Handedness.Right | Handedness.Left)")]
org.mixedrealitytoolkit.core\Utilities\HandsUtils.cs:22:        [Obsolete("Deprecated, please use XRSubsystemHelpers.HandsAggregator")]
org.mixedrealitytoolkit.core\Utilities\PlayspaceUtilities.cs:44:        [ObsoleteAttribute("For transforming poses into world space, use XROrigin.CameraFloorOffsetObject.transform.")]
org.mixedrealitytoolkit.core\Utilities\XRSubsystemHelpers.cs:55:        [Obsolete("GetAllRunningSubsystems now internally caches for you; this separate NonAlloc method is no longer necessary.")]
org.mixedrealitytoolkit.input\Controllers\ArticulatedHandController.cs:50:        [Obsolete("Deprecated, please use XRSubsystemHelpers.HandsAggregator instead.")]
org.mixedrealitytoolkit.input\Interactors\Ray\MRTKRayInteractor.cs:52:        [Obsolete("Deprecated, please use XRSubsystemHelpers.HandsAggregator instead.")]
org.mixedrealitytoolkit.input\Simulation\Devices\ControllerSimulationSettings.cs:61:        [Obsolete("This property is deprecated, use ToggleSecondaryHandshapes instead.")]
org.mixedrealitytoolkit.input\Subsystems\SyntheticHands\SyntheticHandsSubsystem.cs:76:        [Obsolete("Please use the GetNeutralHandshape(handNode) instead.")]
org.mixedrealitytoolkit.input\Subsystems\SyntheticHands\SyntheticHandsSubsystem.cs:84:        [Obsolete("Please use the SetNeutralHandshape(handNode, handshapeId) instead.")]
org.mixedrealitytoolkit.input\Subsystems\SyntheticHands\SyntheticHandsSubsystem.cs:94:        [Obsolete("Please use the GetSelectionHandshape(handNode) instead.")]
org.mixedrealitytoolkit.input\Subsystems\SyntheticHands\SyntheticHandsSubsystem.cs:102:        [Obsolete("Please use the SetSelectionHandshape(handNode, handshapeId) instead.")]
org.mixedrealitytoolkit.input\Subsystems\SyntheticHands\SyntheticHandsSubsystem.cs:469:            [Obsolete("Please use the GetNeutralHandshape(handNode) instead.")]
org.mixedrealitytoolkit.input\Subsystems\SyntheticHands\SyntheticHandsSubsystem.cs:477:            [Obsolete("Please use the SetNeutralHandshape(handNode, handshapeId) instead.")]
org.mixedrealitytoolkit.input\Subsystems\SyntheticHands\SyntheticHandsSubsystem.cs:487:            [Obsolete("Please use the GetSelectionHandshape(handNode) instead.")]
org.mixedrealitytoolkit.input\Subsystems\SyntheticHands\SyntheticHandsSubsystem.cs:495:            [Obsolete("Please use the SetSelectionHandshape(handNode, handshapeId) instead.")]
org.mixedrealitytoolkit.input\Utilities\FollowJoint.cs:42:        [Obsolete("Please change the Hand value on the jointPoseSource instead")]
org.mixedrealitytoolkit.input\Utilities\FollowJoint.cs:52:        [Obsolete("Please change the Joint value on the jointPoseSource instead")]
org.mixedrealitytoolkit.input\Utilities\PoseSource\FallbackCompositePoseSource.cs:23:        [Obsolete, HideInInspector]
org.mixedrealitytoolkit.input\Utilities\PoseSource\FallbackCompositePoseSource.cs:50:        [Obsolete]
org.mixedrealitytoolkit.input\Utilities\PoseSource\HandBasedPoseSource.cs:18:        [Obsolete("Deprecated, please use XRSubsystemHelpers.HandsAggregator instead.")]
org.mixedrealitytoolkit.input\Visualizers\ControllerVisualizer\ControllerVisualizer.cs:50:        [Obsolete("Deprecated, please use XRSubsystemHelpers.HandsAggregator instead.")]
org.mixedrealitytoolkit.spatialmanipulation\Constraints\ConstraintManager.cs:140:        [Obsolete("Use Setup instead for first-time initialization, and OnManipulationStarted for subsequent manipulation.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\Dialog.cs:19:    [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\Dialog.cs:25:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\Dialog.cs:31:        [Obsolete("Legacy Dialog is deprecated. Please migrate to the new Dialog. See uxcore/LegacyDialog/README.md")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\Dialog.cs:37:        [Obsolete("Legacy Dialog is deprecated. Please migrate to the new Dialog. See uxcore/LegacyDialog/README.md")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\Dialog.cs:47:        [Obsolete("Legacy Dialog is deprecated. Please migrate to the new Dialog. See uxcore/LegacyDialog/README.md")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\Dialog.cs:61:        [Obsolete("Legacy Dialog is deprecated. Please migrate to the new Dialog. See uxcore/LegacyDialog/README.md")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\Dialog.cs:75:        [Obsolete("Legacy Dialog is deprecated. Please migrate to the new Dialog. See uxcore/LegacyDialog/README.md")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\Dialog.cs:89:        [Obsolete("Legacy Dialog is deprecated. Please migrate to the new Dialog. See uxcore/LegacyDialog/README.md")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\Dialog.cs:103:        [Obsolete("Legacy Dialog is deprecated. Please migrate to the new Dialog. See uxcore/LegacyDialog/README.md")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\Dialog.cs:117:        [Obsolete("Legacy Dialog is deprecated. Please migrate to the new Dialog. See uxcore/LegacyDialog/README.md")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\Dialog.cs:131:        [Obsolete("Legacy Dialog is deprecated. Please migrate to the new Dialog. See uxcore/LegacyDialog/README.md")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\Dialog.cs:148:        [Obsolete("Legacy Dialog is deprecated. Please migrate to the new Dialog. See uxcore/LegacyDialog/README.md")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\Dialog.cs:158:        [Obsolete("Legacy Dialog is deprecated. Please migrate to the new Dialog. See uxcore/LegacyDialog/README.md")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\Dialog.cs:165:        [Obsolete("Legacy Dialog is deprecated. Please migrate to the new Dialog. See uxcore/LegacyDialog/README.md")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\Dialog.cs:171:        [Obsolete("Legacy Dialog is deprecated. Please migrate to the new Dialog. See uxcore/LegacyDialog/README.md")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\Dialog.cs:178:        [Obsolete("Legacy Dialog is deprecated. Please migrate to the new Dialog. See uxcore/LegacyDialog/README.md")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\Dialog.cs:199:        [Obsolete("Legacy Dialog is deprecated. Please migrate to the new Dialog. See uxcore/LegacyDialog/README.md")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\Dialog.cs:235:        [Obsolete("Legacy Dialog is deprecated. Please migrate to the new Dialog. See uxcore/LegacyDialog/README.md")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\Dialog.cs:278:        [Obsolete("Legacy Dialog is deprecated. Please migrate to the new Dialog. See uxcore/LegacyDialog/README.md")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButton.cs:21:    [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButton.cs:30:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButton.cs:40:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButton.cs:46:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButton.cs:50:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButton.cs:57:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButton.cs:63:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButton.cs:74:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButton.cs:88:        [Obsolete("Use SetLabel or SetButtonContext instead.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButton.cs:95:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButton.cs:110:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButtonContext.cs:20:    [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButtonContext.cs:26:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButtonContext.cs:37:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButtonContext.cs:45:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButtonHelpers.cs:18:    [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButtonHelpers.cs:24:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButtonHelpers.cs:30:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButtonHelpers.cs:36:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButtonTypes.cs:18:    [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButtonTypes.cs:73:    [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogProperty.cs:19:    [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogProperty.cs:28:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogProperty.cs:46:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogProperty.cs:65:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogProperty.cs:85:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogProperty.cs:105:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogProperty.cs:111:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogProperty.cs:117:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogProperty.cs:123:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogProperty.cs:129:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogProperty.cs:135:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogProperty.cs:141:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogShell.cs:23:    [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogShell.cs:33:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogShell.cs:47:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogShell.cs:55:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogShell.cs:59:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogShell.cs:116:        [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogState.cs:18:    [Obsolete("This legacy dialog system has been deprecated. Please migrate to the new dialog system, see MixedReality.Toolkit.UX.DialogPool for more details.")]
org.mixedrealitytoolkit.uxcore\Slider\Slider.cs:143:        [Obsolete("Use Value instead")]

**Comment by AMollis** [comment]
Maintainers discussed, and agreed this should happen with next major release.

This would impact the following packages:

* Core
* UXCore
* Input
* SpatialManipulation

**Comment by shaynie** [comment]
Reevaluate with XRI 3.0 upgrade

**Comment by AMollis** [comment]
@ms-RistoRK  can you remove the Obsolete stuff in the https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/tree/feature/XRI3 branch?

**Comment by ms-RistoRK** [comment]
> @ms-RistoRK can you remove the Obsolete stuff in the https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/tree/feature/XRI3 branch?

Sure, I'll create a Task in the corresponding User Story to address the issue as part of the XRI 3 migration.

**Comment by ms-RistoRK** [comment]
PR for this issue is ready for review: https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/774
