### ISSUE TITLE
[FEATURE REQUEST] Allow developers to set the Rigidbody movement type on ObjectManipulator

### ISSUE THREAD

**Issue by whebertML** [MixedRealityToolkit/MixedRealityToolkit-Unity#532]
ObjectManipulator currently hard codes the manipulation of an object with an attached Rigidbody to be non-kinematic, or "velocity tracking", by setting the rigid body's velocity and angular velocity during fixed updates.  Even if the dev has set the Rigidbody to be kinematic initially, during manipulation it is hard coded to be moved non-kinematically.

Although that works as a default behavior, it would be nice to offer developers the ability to set the type of rigid body movement desired during manipulation (Velocity Tracking, Kinematic, Immediate) for an object, as XRI allows with XRGrabInteractable.

The XRBaseInteractable.MovementType is already an existing type defined in XRI and could be used within ObjectManipulator for this.  Also, the XRBaseInteractor.selectedInteractableMovementTypeOverride can be observed to allow certain interactors to override the movement type as they may call for specific movement in order to be compatible (socket interactors).

Video Demonstrating the issue:

https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/58860572/d8e5bd93-608e-4df9-9d5a-b3fd13606961

**Comment by whebertML** [comment]
PR:  https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/526

**Comment by shaynie** [comment]
Adam to re-review
