### ISSUE TITLE
VirtualizedScrollRectList spawns pool items at an angle[BUG]

### ISSUE THREAD

**Issue by johannes-weidenfeller** [MixedRealityToolkit/MixedRealityToolkit-Unity#534]
## Describe the bug
When using the VirtualizedScrollRectList, the pool item prefabs are spawned as children of scrollRect.content with an initial rotation of Quaternion.identity. If the ScollRect or content are rotated, this will spawn the pool items at an angle to the ScrollRect whereas the desired behaviour is probably to spawn them aligned.

To fix the issue we can replace line 414 in VirtualizedScrollRectList.cs
`GameObject go = Instantiate(prefab, ItemLocation(-(i + 1)), Quaternion.identity, scrollRect.content);`
with
`GameObject go = Instantiate(prefab, ItemLocation(-(i + 1)), scrollRect.content.rotation, scrollRect.content);`
which produces the expected behaviour.

## To reproduce

1. Add a virtualized scroll rect list to a canvas in the scene
2. Rotate the (parent of the) canvas by some angle 

## Expected behavior

The children should spawn aligned with the ScrollRect/its parent canvas.

## Screenshots

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/54772951/83c02319-9b54-47d5-a05f-566bb80b2fdf)

## Your setup (please complete the following information)

- Unity Version 2021.3.19f1
- MRTK Version 3.0.0-pre.18

**Comment by shaynie** [comment]
@johannes-weidenfeller Thanks for the bug report.  Your proposed solution works as written, would you like to submit a pull request?  Please see the contributor guide if you'd like to submit the fix, otherwise we'll add it to the backlog and get it in a uxcore package release.
