### ISSUE TITLE
[BUG]The name 'FindObjectsSortMode' does not exist in the current context

### ISSUE THREAD

**Issue by xxx-x-x** [MixedRealityToolkit/MixedRealityToolkit-Unity#542]
## Describe the bug
Follow the official documents.create a new Unity project with **Unity 2021.3.4f1** and import required dependencies and MRTK3 packages with Mixed Reality Feature Tool.An error was reported after reopening the project.
**Yes, it sounds ridiculous.**I checked google, stackoverflow, official FAQ and ISSUS, and didn't see anyone having related questions.

The software [Mixed Reality Feature Tool](https://learn.microsoft.com/zh-cn/windows/mixed-reality/develop/unity/welcome-to-mr-feature-tool)can be used normally half a year ago,but now importing mrtk3 will be returned and did not import MRTK3 into my project.

## To reproduce

1. Import required dependencies and MRTK3 packages with Mixed Reality Feature Tool.
2. An error was reported after reopening the project.

## Expected behavior

Under normal circumstances, no errors should be reported

## Screenshots
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/55052123/1857e877-4788-40ce-8330-53ae7c5af0d6)
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/55052123/653b799e-2c86-455e-99bc-4439afebe9cc)

## Your setup (please complete the following information)

- Unity Version 2021.3.4f1 **URP**
- MRTK Version  v3.0

## Target platform (please complete the following information)

- HoloLens 2

## Additional context
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/55052123/cee77716-0cdc-4093-9ee3-4e85d7422551)
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/55052123/8f4a07ea-8071-4a17-a15b-b358d1bbb2b9)
After commenting the relevant functions, the project can be used normally for the time being (not sure what will happen later)

**Comment by AMollis** [comment]
@marlenaklein-msft can you take a look at this?  I think you've already addressed this with the follow PR:

- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/515

**Comment by AMollis** [comment]
@xxx-x-x  this fix has been shipped, please update to latest packages and try again.

**Comment by marlenaklein-msft** [comment]
(This issue should be addressed with https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/484 and the [core v3.0.1] patch release).
