### ISSUE TITLE
[BUG] TMPro Input fields pops system keyboard unexpectedly during grab input panel.

### ISSUE THREAD

**Issue by FelixLenainInod** [MixedRealityToolkit/MixedRealityToolkit-Unity#550]
## Describe the bug

Hi, I'm using several MRTKTMP inputFields in a UI canvas to fill up informations and once i have an inputfield edited if i do the pinch gesture it triggers the field and open the keyboard, i'd realy like to get rid of this anoying behaviour but i can't figure out what it is causing this.

Regards

## To reproduce

1. UIcanvas with anMRTKTMP inputfield
2. poke the inputfield
3. edit the input field using keyboard
4. validate the input using keyboard enter
5. pinch gesture opens the keyboard again.

## Expected behavior

pinch gesture not triggering the keyboard after editing an inputfield

## Your setup (please complete the following information)

- Unity Version [e.g. 2021.3.27f1]
- MRTK 3.0

## Target platform (please complete the following information)

- HoloLens 2

**Comment by AMollis** [comment]
@FelixLenainInod is one of the MRTK interactors focusing the input field during the pinch gesture (e.g. is the hard ray on the input field during gesture)?  If yes, then bringing up the keyboard is expected.

**Comment by FelixLenainInod** [comment]
Hi, in my project, FarRay and GazePinch intreractor are disabled only Grab and IndexTipPoke interactors remain active on both hands, I probably should be missing something.
It seems like the inputfield stays focused after editing and the pinch gesture is triggering it, and it happens even when i'm trying to grab a 3D object in the scene.

**Comment by AMollis** [comment]
I see.  If you have a simple scene/app that demonstrates this behavior, can you please share?


@ms-RistoRK , can you please investigate?

**Comment by FelixLenainInod** [comment]
Hi guys, 

I figured this out, it comes from the XR UI InputModule when the Active Input Mode is set to Input Manager Binding, which is default, last selected Dropdown or InputField are triggered by the pinch gesture, and once  Active Input Mode set to Input System Actions everything comes into place.

Hope it can help other

Thank @AMollis for your support

Regards
