### ISSUE TITLE
[BUG] MRTK doesn't work on offline machines

### ISSUE THREAD

**Issue by Warren93** [MixedRealityToolkit/MixedRealityToolkit-Unity#554]
I downloaded this thing onto a machine with network access.  I opened the template project. I ran several of the example scenes. Everything worked fine. I then copy/pasted it to a non networked machine (since my employer has various restrictions on network access). I made sure the directory path on the offline machine was exactly the same as on the online machine (D:/projects/unity/...) just in case there are any cached file paths or whatever. So essentially the project copied to the offline machine was exactly the same as on the online machine (same path, same unity version used to open it, etc.). But when I try to open the project on the offline machine it says there are compilation errors. Why? All the generated library files/packages/cache/whatever have been transferred, nothing should need to be downloaded, it's the same file paths for everything....what gives?

Steps to reproduce:
- Download MixedRealityToolkit-Unity to a machine with network access
- Transfer to an offline machine
- Observe that the transferred project doesn't work (you can try deleting the Library and Temp folders; it won't make a difference)

**Comment by shaynie** [comment]
@Warren93, could you please provide the compilation errors you are seeing?  Thanks

**Comment by Warren93** [comment]
[all errors.txt](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/files/13420786/all.errors.txt)
Attached the full error list.

Based on past experience, if you open a Unity project on an online machine, allow it to download all necessary packages, and then copy the whole project to an offline machine, it just works (unless you delete Library/PackageCache, of course). This is the only case I've seen where Unity seemingly decides for some reason to try to re-download packages, which of course doesn't work when offline. I'm guessing this has to do with the significant number of packages that are external to the project.

Also, I modified the package manifest:

`{
  "dependencies": {
    "com.atteneder.gltfast": "file:../../../ManuallyDownloadedDependencies/glTFast-4.8.3",
    "com.atteneder.ktx": "file:../../../ManuallyDownloadedDependencies/KtxUnity-2.1.2",
    "com.microsoft.mixedreality.openxr": "file:../../../ExternalDependencies/com.microsoft.mixedreality.openxr-1.7.0.tgz",
    "com.microsoft.mixedreality.visualprofiler": "file:../../../ManuallyDownloadedDependencies/com.microsoft.mixedreality.visualprofiler-3.3.0.tgz",
    "com.microsoft.mrtk.graphicstools.unity": "file:../../../ManuallyDownloadedDependencies/com.microsoft.mrtk.graphicstools.unity-0.5.0.tgz",
    "com.microsoft.mrtk.tts.windows": "file:../../../ExternalDependencies/com.microsoft.mrtk.tts.windows-1.0.1.tgz",
    "com.microsoft.spatialaudio.spatializer.unity": "file:../../../ExternalDependencies/com.microsoft.spatialaudio.spatializer.unity-2.0.37.tgz",
    "com.unity.collab-proxy": "2.0.3",
    "com.unity.ide.rider": "3.0.18",
    "com.unity.ide.visualstudio": "2.0.17",
    "com.unity.ide.vscode": "1.2.5",
    "com.unity.inputsystem": "1.6.1",
    "com.unity.mobile.android-logcat": "1.3.2",
    "com.unity.performance.profile-analyzer": "1.2.2",
    "com.unity.test-framework": "1.1.33",
    "com.unity.textmeshpro": "3.0.6",
    "com.unity.timeline": "1.6.4",
    "com.unity.ugui": "1.0.0",
    "com.unity.xr.arcore": "5.0.5",
    "com.unity.xr.arfoundation": "5.0.5",
    "com.unity.xr.interaction.toolkit": "2.3.1",
    "com.unity.xr.management": "4.3.3",
    "com.unity.xr.openxr": "1.7.0",
    "org.mixedrealitytoolkit.accessibility": "file:../../../org.mixedrealitytoolkit.accessibility",
    "org.mixedrealitytoolkit.audio": "file:../../../org.mixedrealitytoolkit.audio",
    "org.mixedrealitytoolkit.core": "file:../../../org.mixedrealitytoolkit.core",
    "org.mixedrealitytoolkit.data": "file:../../../org.mixedrealitytoolkit.data",
    "org.mixedrealitytoolkit.diagnostics": "file:../../../org.mixedrealitytoolkit.diagnostics",
    "org.mixedrealitytoolkit.extendedassets": "file:../../../org.mixedrealitytoolkit.extendedassets",
    "org.mixedrealitytoolkit.input": "file:../../../org.mixedrealitytoolkit.input",
    "org.mixedrealitytoolkit.spatialmanipulation": "file:../../../org.mixedrealitytoolkit.spatialmanipulation",
    "org.mixedrealitytoolkit.standardassets": "file:../../../org.mixedrealitytoolkit.standardassets",
    "org.mixedrealitytoolkit.tools": "file:../../../org.mixedrealitytoolkit.tools",
    "org.mixedrealitytoolkit.uxcomponents": "file:../../../org.mixedrealitytoolkit.uxcomponents",
    "org.mixedrealitytoolkit.uxcomponents.noncanvas": "file:../../../org.mixedrealitytoolkit.uxcomponents.noncanvas",
    "org.mixedrealitytoolkit.uxcore": "file:../../../org.mixedrealitytoolkit.uxcore",
    "org.mixedrealitytoolkit.windowsspeech": "file:../../../org.mixedrealitytoolkit.windowsspeech",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  },
  "testables": [
    "com.unity.inputsystem",
    "org.mixedrealitytoolkit.accessibility",
    "org.mixedrealitytoolkit.core",
    "org.mixedrealitytoolkit.data",
    "org.mixedrealitytoolkit.diagnostics",
    "org.mixedrealitytoolkit.extendedassets",
    "org.mixedrealitytoolkit.input",
    "org.mixedrealitytoolkit.spatialmanipulation",
    "org.mixedrealitytoolkit.standardassets",
    "org.mixedrealitytoolkit.uxcomponents",
    "org.mixedrealitytoolkit.uxcomponents.noncanvas",
    "org.mixedrealitytoolkit.uxcore",
    "org.mixedrealitytoolkit.windowsspeech"
  ]
}
`

....to not try to download dependencies and instead use ones that I downloaded manually. I checked that this worked by cutting the internet to my online machine and reopening the project. It worked fine. I only ran into problems when transferring the project to the offline machine (Same drive letter on the offline machine, same directory path).

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/5239939/f897931e-8c61-43a3-a120-6e96c56aaccd)

**Comment by shaynie** [comment]
@Warren93, thanks for the reply.  I looked through the errors, and the packages didn't get their dependencies downloaded.  You can either copy the library folder from the online machine to the offline machine so that the package cache is available, or manually download the dependency packages from Unity.  You can look at the Library\PackageCache folder to see which packages were required.

**Comment by shaynie** [comment]
Closing this.  The workarounds above should resolve your issue.

**Comment by Warren93** [comment]
It is perhaps worth noting (for anyone who comes across this and wasn't already aware) that on Windows Unity keeps an additional package cache in %localappdata%\Unity. Copying that one to the offline machine was what fixed the problem for me.
