### ISSUE TITLE
[BUG] Initial scale of `BoundsHandleInteractable` is not taken into account on initialization

### ISSUE THREAD

**Issue by anonymous2585** [MixedRealityToolkit/MixedRealityToolkit-Unity#572]
## Describe the bug

The initial scale relative to the parent is not taken into account on handles initialization.

I also expect the initial transform scale on each handles in the prefab to be taken in account for the scaling. That way, a user can do a prefab with big handles, one other with smaller handles...

I also think it's better to take the minimum (actual is maximum) of the parent lossy scale, so handles doesn't risk to collide on the shorter side.

## To reproduce

1. Import [this Unity package](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/files/13527314/BoundsHandlesSize.zip)
2. Open scene `BoundsControlIssue`
3. Open prefab `BoundingBoxWithTraditionalHandlesNoMaintainGlobalSize`, see the scale of handles is very big (100) and maintain global scale is unckecked
4. Close prefab
5. Press play
6. See issue (handles scale should have been as big as in the prefab, in fact too big to be usable)
7. Open prefab `BoundingBoxWithTraditionalHandlesNoMaintainGlobalSize`, set the scale of handles to a standard value (10)
8. Close prefab
9. Press play
10. See realtime scale is still the same as in step 6 and still too small

## Expected behavior

The initial handles scale is the same as if a user grabed the prefab (scaled 1x1x1, handles scale to 10 like in step 10) and extended it to a 15x6x10 scale:
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/148471165/e9a23d85-8144-4b9b-bf68-348e3fd593b3)

## Screenshots

Actual result is a big box with really small handles hard to grab:
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/148471165/ef8f2f49-90a5-4c99-93ac-54f809b9e8b1)

## Setup

- Unity Version 2021.3.21f1
- MRTK Version or Commit: main branch [a09f5cd](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/commit/a09f5cd98b2b47b668bcc6fc775bcc7fd3735eb7)

## Target platform

- HoloLens 2
- HP Reverb G2
- iOS AR
- OpenXR

**Comment by marlenaklein-msft** [comment]
@anonymous2585 Thanks for filing this issue! #598 will provide an ability to change handle size via the handle transforms on the bounding box prefab. By default, this sets the global scale of the handle to 1, but this can now be adjusted to be larger or smaller from the prefab.

For the parent lossy scale, taking the minimum value is not desired mainly because of instances of flat panels where the z-value is near 0.
