### ISSUE TITLE
[BUG] [EDITOR] Edition of multiples interactables property `IsInteractive` at the same time doesn't work

### ISSUE THREAD

**Issue by anonymous2585** [MixedRealityToolkit/MixedRealityToolkit-Unity#573]
## Describe the bug

When you select multiples Pressables Buttons and check or uncheck the "IsInteractive" property, only the last one selected is actually enabled or disabled.

## To reproduce

1. Open the scene `Experimental/ScrollingExample`
2. Unfold all children of the GameObject `VerticalAndHortizontalScrolling`
3. Select all children called `Action Button (x)`
4. In the inspector, uncheck `Is Interactable`
5. See only the last selected is disabled

## Expected behavior

All selected Pressables Buttons are disabled.

## Setup

- Unity Version 2021.3.21f1
- MRTK Version or Commit: main branch [a09f5cd](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/commit/a09f5cd98b2b47b668bcc6fc775bcc7fd3735eb7)

## Additional information

The work-around is to uncheck the Unity enabled property that is synced with the "IsInteractive" value.

I personnaly think it's better to have only one checkbox in the insperctor. The "IsInteractable" checkbox is not so useful and confusing that it also disable the component at the same time.
I'm in favor to remove it and document that a disabled button is just a disabled interactable component.

**Comment by AMollis** [comment]
Hi @anonymous2585 ,

Thank you for reporting this issue or requesting this feature. We appreciate your feedback and interest in MRTK3.

We have reviewed your issue or feature request and confirmed that it is valid. We have added it to our backlog and will prioritize it accordingly.

However, if you would like to speed up the process and contribute to the MRTK3 project, you are welcome to submit a Pull Request with your proposed fix or implementation. We would be happy to review your code and merge it into the main branch if it meets our quality standards.

Please let us know if you have any questions or need any assistance. Thank you for your support and collaboration.

Best regards,
The MRTK3 team

**Comment by anonymous2585** [comment]
@ms-RistoRK, I'm sorry, but I just tested on the main branch @ e25a7a8, and the issue is not fixed. Moreother, it has introduced #772...

Please reopen the issue. #772 is more important than this issue.
