### ISSUE TITLE
[BUG] Hand ray and reticule are hidden when scrolling a scrollable from a disabled child interactable

### ISSUE THREAD

**Issue by anonymous2585** [MixedRealityToolkit/MixedRealityToolkit-Unity#574]
## Describe the bug

Hand ray and reticule are hidden when scrolling a scrollable from a disabled child interactable.

## To reproduce

1. Open the scene `Experimental/ScrollingExample`
2. Unfold all children of the GameObject `VerticalAndHortizontalScrolling`
3. Uncheck `Is Interactable` on some of the children called `Action Button (x)`
4. Press play and test with the hand simulator, see ray hidden when the scrolling starts with the ray on one of the disabled buttons (edit: now I have no scroll at all, but the ray doesn't disappear)
4. Build the and run on Hololens 2, see same thing

## Expected behavior

Hand ray and reticule are always visible when scrolling in a scrollable.

## Setup

- Unity Version 2021.3.21f1
- MRTK Version or Commit: main branch [a09f5cd](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/commit/a09f5cd98b2b47b668bcc6fc775bcc7fd3735eb7)

## Target platform (please complete the following information)

- HoloLens 2
- HP Reverb G2
- OpenXR

**Comment by AMollis** [comment]
@anonymous2585  can you provide a video of the failure?

**Comment by anonymous2585** [comment]
Here is an Hololens video:
https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/148471165/482c7c52-e613-4204-8b0d-fa0c555d86b5
At first, I clicked on a not interactable (IsInteractable = false) button, ray desappeared but movements are ok. Then I show it's ok with an activated button.

Here is a view in editor:
![BugDisabledButtonsEditor](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/148471165/de5bf848-d341-4594-826a-ac597ea0fe38)
At first I clicked on a not interactable (IsInteractable = false) button, movements didn't work at all. Then I show it's ok with an activated button.

**Comment by AMollis** [comment]
Hi @anonymous2585,

Thank you for reporting this issue or requesting this feature. We appreciate your feedback and interest in MRTK3.

We have reviewed your issue or feature request and confirmed that it is valid. We have added it to our backlog and will prioritize it accordingly.

However, if you would like to speed up the process and contribute to the MRTK3 project, you are welcome to submit a Pull Request with your proposed fix or implementation. We would be happy to review your code and merge it into the main branch if it meets our quality standards.

Please let us know if you have any questions or need any assistance. Thank you for your support and collaboration.

Best regards,
The MRTK3 team

**Comment by AMollis** [comment]
@anonymous2585 , the problem here appear to the be that disabled interactor has its collider still enabled.  If you disable the collider, your scenario works.   

Changing this to feature request to make "collider disablement easier on interactors".  I have a solution for this here:
- https://github.com/AMollis/MixedRealityToolkit-Unity-AMollis-NEW/tree/user/amollis/auto-disable-button-collider-and-pressable-button-disable

I'll be making a PR soon-ish

**Comment by AMollis** [comment]
Here's the PR:

- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/626
