### ISSUE TITLE
[BUG] Far ray bends otwards when it is closer to the edge of view

### ISSUE THREAD

**Issue by Ali-Can-Keskin** [MixedRealityToolkit/MixedRealityToolkit-Unity#580]
## Describe the bug

When using MRTK3 with Quest devices (2,3 and Pro) if you turn your head away from the ray's endpoint so that it is close to the edge it starts bending outwards.

## To reproduce

1. Have a basic UI or use samples
2. Deploy it to any Quest device
3. Aim for a button or anything
4. Look to your side, so that the ray and its endpoint is close to the edge of your view
5. You will notice the endpoint/reticle is moving even though you only move your head not your hand

## Expected behavior

The line should not bend in anyway depending on your headpose/ head movement/ view position.

## Your setup (please complete the following information)

- Unity Version 2021.3.32f1
- MRTK Version 3

## Target platform (please complete the following information)

- OpenXR
- Quest

**Comment by whebertML** [comment]
@Ali-Can-Keskin   This issue may be a duplicate/similar to issue #548 

There is a potential fix to this issue with PR #625 

If you would like, you could test the new hand ray pose source to see if it addresses the issue you were seeing.

**Comment by Ali-Can-Keskin** [comment]
Thank you, I will test it once I get a chance.
