### ISSUE TITLE
[BUG] keep simulated hands (keys T and Y)  a.k.a toggle don't keep the gesture

### ISSUE THREAD

**Issue by Maesla** [MixedRealityToolkit/MixedRealityToolkit-Unity#594]
## Describe the bug

Key T for left hand and Y for right hand keep the hand but doesn't keep the gesture.
This makes very difficult to simulate the scaling by two hands with an object manipulator

## To reproduce

1. Go to MRTKDevTemplate
2.  Open HandInteractionExample
3. Press play
4. Go to the coffee cup with the simulated left hand, and grab it with the input simulator
     - Press and hold left shift to show left hand
     - Go to the coffee cup
     - Press mouse left button
     - Move the mouse to be sure that the coffee cup is grabbed
5. Press key "T" to keep the hand
6. Release left shift
7. See how the hand is kept, but not the grabbing gesture

## Expected behavior

Grabbing gesture is kept after pressing key "t", so it is possible to simulate the right hand and simulate the scaling with two hands procedure.
This was the  behavior in MRTK 2.x

## Your setup (please complete the following information)

- Unity Version 2021.3.31f
- MRTK Version or Commit 
org.mixedrealitytoolkit.core: 3.0.1
org.mixedrealitytoolkit.input: 3.0.0
org.mixedrealitytoolkit.spatialmanipulation: 3.0.0
org.mixedrealitytoolkit.standardassets: 3.0.0
org.mixedrealitytoolkit.uxcomponents: 3.1.0
org.mixedrealitytoolkit.uxcore: 3.1.0
org.mixedrealitytoolkit.tools: 3.0.0
org.mixedrealitytoolkit.uxcomponents.noncanvas: 3.1.0
org.mixedrealitytoolkit.accessibility: 1.0.0-pre.18
org.mixedrealitytoolkit.audio: 3.0.0
org.mixedrealitytoolkit.diagnostics: 3.0.0
org.mixedrealitytoolkit.extendedassets: 3.0.0
org.mixedrealitytoolkit.windowsspeech: 3.0.0

## Target platform (please complete the following information)

- Unity Editor

**Comment by AMollis** [comment]
@Maesla, good idea. We welcome community contributions to the project.  Please feel free to make this change.

**Comment by AMollis** [comment]
Hi @Maesla,

Thank you for reporting this issue or requesting this feature. We appreciate your feedback and interest in MRTK3.

We have reviewed your issue or feature request and confirmed that it is valid. We have added it to our backlog and will prioritize it accordingly.

However, if you would like to speed up the process and contribute to the MRTK3 project, you are welcome to submit a Pull Request with your proposed fix or implementation. We would be happy to review your code and merge it into the main branch if it meets our quality standards.

Please let us know if you have any questions or need any assistance. Thank you for your support and collaboration.

Best regards,
The MRTK3 team
