### ISSUE TITLE
[BUG] MRTK Builds generate unremovable temporary files

### ISSUE THREAD

**Issue by antonvalletas** [MixedRealityToolkit/MixedRealityToolkit-Unity#596]
## Describe the bug

MRTK build produce temporary files that cannot be removed from the HL2 memory, not by clearing or uninstalling the application. Basically what is being said here:

https://learn.microsoft.com/en-us/answers/questions/732279/unable-to-delete-hololens-2-temporary-files-after?orderby=newest#answers

https://github.com/microsoft/Microsoft-OpenXR-Unreal/issues/76

## To reproduce

1. Deploy app to HL2
2. Since we don't have access to the protected filesystem, we cant check which files are being left behind and are undeletable, but we have to reset out HL2 every other month. 

## Expected behavior

Application installs don't leave leftover files that cannot be removed/cleaned

## Your setup (please complete the following information)

Happens both on MRTK and Unreal Engine builds as stated in the previous links as this is probably a bug in HL2 not MRTK itself. 

## Target platform (please complete the following information)

- HoloLens 2

**Comment by AMollis** [comment]
This is not an MRTK issue.  
 
 Note, the HL2 bug you are describing is an OS bug, and is currently being addressed.  The issue is documented here:
 
 https://learn.microsoft.com/en-us/hololens/hololens-troubleshooting#users-may-be-unable-to-cleanup-temporary-files-completely
