### ISSUE TITLE
Unable to see Skybox in Game mode - Black color only

### ISSUE THREAD

**Issue by abhilashca** [MixedRealityToolkit/MixedRealityToolkit-Unity#606]
## Describe the bug

I am experimenting with MRTK3 following the steps outlined in https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/getting-started/setting-up/setup-new-project. I noticed that while running the project, I am unable to see the skybox (which was not the case with MRTK v2.x). Instead black screen is been displayed. But, I am able to see the hand simulation. Here is a quick screenshot:

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/12084395/32963565-8300-488b-a70e-f730aa2eb961)

The issue is reproducible in `MRTKDevTemplate` project template.

## To reproduce

1. Clone https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/tree/main/UnityProjects/MRTKDevTemplate
2. Create an empty scene
3. Add `MRTK XR Rig` and `MRTKInputSimulation`
4. Run the project
5. Black screen comes instead of Skybox

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/12084395/595a108e-b542-437d-a33f-ea9970a3e8dc)

## Expected behavior

Play mode should show Skybox or virtual environment in the case of VR, instead of black screen.

## Your setup

- Unity Version 2022.3.11f1
- MRTK Version 
```
org.mixedrealitytoolkit.input: 3.0.0
org.mixedrealitytoolkit.uxcomponents: 3.1.0
org.mixedrealitytoolkit.core: 3.0.1
org.mixedrealitytoolkit.uxcore: 3.1.0
org.mixedrealitytoolkit.spatialmanipulation: 3.0.0
org.mixedrealitytoolkit.standardassets: 3.0.0
org.mixedrealitytoolkit.uxcomponents.noncanvas: 3.1.0
org.mixedrealitytoolkit.audio: 3.0.0
org.mixedrealitytoolkit.diagnostics: 3.0.0
org.mixedrealitytoolkit.extendedassets: 3.0.0
org.mixedrealitytoolkit.tools: 3.0.0
org.mixedrealitytoolkit.windowsspeech: 3.0.0
```

## Target platform (please complete the following information)

- Oculus 2 (with URP)

## Additional context

While running `BoundsControlExample` scene from `MRTKDevTemplate` project, I noticed that background is black. Is that the default behavior?
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/12084395/d9340638-f460-4c29-bede-bf7dc4cd8c60)

Not sure whether I am missing any configurations here.

**Comment by anonymous2585** [comment]
The main camera in the MRTK XR Rig prefab has a `Camera Settings Manager` component that manage the clear mode of the camera.

Make sure to set the "Clear Mode" for opaque display in this component to "Skybox".

Here is my setup to show the skybox in VR:
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/148471165/12010ab5-9f97-44d3-b302-9a30ca713bbe)

**Comment by AMollis** [comment]
@abhilashca  I believe this was already addressed with this change

- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/517

The clear color's alpha was not 0.   Can you please try the code in the "main" branch?
