### ISSUE TITLE
Dots instancing compatible Graphics Tools shaders 

### ISSUE THREAD

**Issue by Merichbier** [MixedRealityToolkit/MixedRealityToolkit-Unity#610]
## Describe the problem

When using [Entities Graphics](https://docs.unity3d.com/Packages/com.unity.entities.graphics@1.0/manual/index.html), the Standard shader can't be used as it isn't dots instancing compatible. 

## Describe the solution you'd like

Make the shaders in graphics tools Dots instancing compatible.
https://docs.unity3d.com/Packages/com.unity.entities.graphics@1.0/manual/dots-instancing-shader.html

## Describe alternatives you've considered

Use a different shader.

## Additional context
-

**Comment by AMollis** [comment]
Hi @Merichbier ,  please open this issue in the Graphics Tools repository here:

https://github.com/microsoft/MixedReality-GraphicsTools-Unity/issues
