### ISSUE TITLE
[FEATURE REQUEST] Add Slider.SetValueWithoutNotify

### ISSUE THREAD

**Issue by Maesla** [MixedRealityToolkit/MixedRealityToolkit-Unity#627]
## Describe the problem

Sometimes you need to update the UI but you don't want to trigger the event
https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/blob/0bf1b5c5e0e74c30e37930b6c430e2258b9e8ff5/org.mixedrealitytoolkit.uxcore/Slider/Slider.cs#L149
Imagine this scenario

```csharp
public class DebugClass
{
	public Slider slider;
	public PressableButton button;
	public Foo foo;
	
	private void OnEnable()
	{
		slider.OnValueUpdated.AddListener(UpdateFoo);
		button.OnClicked.AddListener(ResetFoo);
	}
	
	private void UpdateFoo(SliderEventData sliderValue)
	{
		foo.SetValue(sliderValue);
	}
	
	private void ResetFoo()
	{
		float resetValue = 0f;
		foo.SetValue(resetValue);
		slider.Value = resetValue; // this line raises slider.OnValueUpdated. 
		//slider.SetValueWithoutNotify(resetValue); => this would solve the issue
	}
}
```
When you press the button, you reset the foo object and update the slider so you can represent the new value of the object. However, because you did modify the slider, the OnValueUpdated event is fired, triggering UpdateFoo, which is a redundant logic. You should be able to modify the slider without raising the event

## Describe the solution you'd like

Add a method to modify the slider value without raising the event.
That's the UGUI solution
slider.SetValueWithoutNotify(newValue);
https://docs.unity3d.com/ScriptReference/UIElements.Slider.html
## Describe alternatives you've considered

Adding a flag in my own class to track if the event is valid or not

## Additional context
N/A

**Comment by AMollis** [comment]
I would recommend against this functionality.  Other listeners may want to receive such events.  The handlers of the event change should decide if and when it wants to handle change events, not the caller.  The caller doesn't have enough knowledge to make this determination.

 @Maesla , in the scenario you presented, you can prevent the unwanted handling of the event by removing handlers during the "reset". You could also use a flag to determine if you are "resetting".  Or in you can update "foo" to check that value hasn't actually changed.

Leaving bug open to confirm "won't fix" with other maintainers.

**Comment by shaynie** [comment]
Discussed in Maintainer sync, consensus is to not change the functionality.

**Comment by Maesla** [comment]
I see your point. Actually, I am currently using a flag to discard the undesired event.

However, I still think it is useful, and the method name is quite verbose and the intention of the method is clear.

Unity uses this approach and even MRTK uses it in StateFullInteractable
https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/blob/0bf1b5c5e0e74c30e37930b6c430e2258b9e8ff5/org.mixedrealitytoolkit.core/Interactables/StatefulInteractable.cs#L298

Anyway, I'll keep using the flag.

Thanks!
