### ISSUE TITLE
Release MRTK3 Packages at commit d9ff8b0

### ISSUE THREAD

**Issue by AMollis** [MixedRealityToolkit/MixedRealityToolkit-Unity#628]
This is tracking the release of packages at commit https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/commit/d9ff8b079f8de0c43348ab8c1f3952c6ced2a483

**Draft release**
https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/releases/tag/untagged-351a9114a3fc7174f496

**Comment by AMollis** [comment]
@MixedRealityToolkit/mixedrealitytoolkit-unity-maintainers  please add a sign-off comment once your organization approves release.

* **Qualcomm**: @keveleigh or @david-c-kline 
* **Magic Leap**: @whebertML  or @ghazen-ml 
* **Microsoft**: @shaynie  or @AMollis

**Comment by whebertML** [comment]
@AMollis   Tested release tarballs on ML2, all works as expected.  Approved.

**Comment by shaynie** [comment]
[like]  Scott Haynie reacted to your message:
________________________________

**Comment by shaynie** [comment]
Tested and approved by shaynie

**Comment by keveleigh** [comment]
Found a regression: https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/636

**Comment by shaynie** [comment]
Branched, cherry picked #636, and will replace the input tgz in the draft release.

**Comment by keveleigh** [comment]
Approved! :shipit:

**Comment by shaynie** [comment]
Released, 2-9-24. https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/releases/tag/core-v3.1.1
