### ISSUE TITLE
Verify package versions are updated correctly for #492 and #580

### ISSUE THREAD

**Issue by AMollis** [MixedRealityToolkit/MixedRealityToolkit-Unity#642]
Package versions might be invalidate after the last release.  Please validate that the packages impacted by this change have the correct version:

* https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/580
* https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/492

**Comment by whebertML** [comment]
PR: #662
