### ISSUE TITLE
HP Reverb profile warning in sample scenes

### ISSUE THREAD

**Issue by marlenaklein-msft** [MixedRealityToolkit/MixedRealityToolkit-Unity#647]
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/125413876/e1d6b8b6-b005-4386-9c58-d7165f9b2f0c)

When opening the MRTK3 sample scenes (2022.3.17), this warning is logged. Profile comes from the Unity OpenXR package, our OpenXRPackageSettings should be updated to remove the deprecated controller profile

**Comment by MaxPalmer-UH** [comment]
Tried in Unity 2022, also can't force the warning.

**Comment by MaxPalmer-UH** [comment]
Closing as not reproducible
