### ISSUE TITLE
[BUG/Problem]: MRTK3 and WebView2 cause application to crash

### ISSUE THREAD

**Issue by ArDevKarl** [MixedRealityToolkit/MixedRealityToolkit-Unity#650]
## Issue:

We recently updated our HoloLens 2 project from MRTK2.8.3 to MRTK3. Unfortunetly I just found out, that the WebView2 (from MRFeatureTool) seems to be not supported by MRTK3 (https://github.com/MicrosoftEdge/WebView2Feedback/issues/3516). I tried this and the app just crashes without noticifactions or errors. Everything seems to work fine, until I try to initialize a WebView.

This would be a major setback for our development. Are there any plans for this or known workarounds, to run WebVew2 with a MRTK3 application for HoloLens 2?

## Steps to reproduce the behavior:

Setup the MRTK3 DevTemplate and implement the WebView2 package. Put the WebView Prefab inside a scene, build and run it on the HoloLens. App will crash as soon the WebView is initialized.

## Expected behavior
- The application does not crash
- Logs give me information about any occuring errors or incompadibilities

## Your setup (please complete the following information)
- Unity 2022.3.7f1
- MRTK3 
- WebView2 (0.17.1-pre.5)
(FYI: Works fine in UnityEditor)

Target platform:
- HoloLens 2

**Comment by AMollis** [comment]
Hi @ArDevKarl , thank you for your bug report.  This is a WebView2 issue.  As such I've open a WebView2 bug under their repository.  Please track new issue: 

- https://github.com/MicrosoftEdge/WebView2Feedback/issues/4386

Thank you!

**Comment by michaelfarnsworth** [comment]
@ArDevKarl we have no explorer supporting XAML Unity apps for WebView2. Could you achieve what you're wanting with a UWP app?

**Comment by ArDevKarl** [comment]
@michaelfarnsworth No, we had to roll back to MRTK2.8.3 because of this problem. Are there any plans on supporting WebView2 together with MRTK3? We'd really like to update to MRTK3 for upcoming realeases. Thank you, for the reply.

**Comment by michaelfarnsworth** [comment]
Unfortunately, we don't currently have anything slated in terms of supporting MRTK3 + XAML in Unity.
