### ISSUE TITLE
[FEATURE REQUEST] Update code per latest PR#611 feedback.

### ISSUE THREAD

**Issue by ms-RistoRK** [MixedRealityToolkit/MixedRealityToolkit-Unity#651]
@keveleigh kindly provided additional feedback for [PR 611](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/611).  This issue to is to track his feedback and improve the code accordingly.

**Comment by ms-RistoRK** [comment]
Implementation of the additional feedback is being implemented here: https://github.com/ms-RistoRK/MixedRealityToolkit-Unity/tree/FeatureRequest651UpdateCodePerPR611Feedback

**Comment by ms-RistoRK** [comment]
I had to create a new PR as the previous one was not picking up latest commits.  The new PR is in review here: https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/659

**Comment by keveleigh** [comment]
@ms-RistoRK Thanks for opening this issue! I was out for a few days the last few weeks and meant to before I left...thanks again!

**Comment by ms-RistoRK** [comment]
Friendly notification: there is another person already submitting a code-change for StateVisualizer: https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/584

**Comment by ms-RistoRK** [comment]
This issue has already been addressed in https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/659

**Comment by ms-RistoRK** [comment]
This issue has already been addressed in https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/659 closing it.
