### ISSUE TITLE
[BUG] Slider (non-canvas) wrong scaling

### ISSUE THREAD

**Issue by Daniel4144** [MixedRealityToolkit/MixedRealityToolkit-Unity#652]
## Describe the bug

The slider components do not scale correctly (NonCanvasSliderBase, Slider_168x40mm_Base), see screenshot below. The line does not fit with scales other than 1.

## Screenshots

![grafik](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/49939834/3901f910-e4b4-4a32-a7da-cb5842cb6fa8)
Scale = 2

## Your setup (please complete the following information)

- Unity Version 2022.3.12f1
- MRTK UX  v3.1.1

**Comment by AMollis** [comment]
@Daniel4144 , is the problem that the backplate does not scale with the slider bar?

**Comment by Daniel4144** [comment]
No, it is only the line of the slider that does not scale correctly. I looked into it and found that its local scale is applied depending on the world positions of the Start and End transforms.

Transforming the SliderTrackDirection vector to local coordinates fixes the issue:
  ```csharp
//SliderVisuals.cs line 89
Vector3 localSliderTrackVector = trackArea.parent.InverseTransformVector(SliderState.SliderTrackDirection); //does trackArea always have a parent?
trackArea.localScale = new Vector3(localSliderTrackVector.magnitude, trackArea.localScale.y, trackArea.localScale.z);
```

**Comment by AMollis** [comment]
@Daniel4144 , if you have a potential fix, feel free to make a Pull Request, and we will review.    This might be quicker than waiting for one of the maintainers to fix.
