### ISSUE TITLE
[BUG] MRTKDevTemplate Project compilation errors

### ISSUE THREAD

**Issue by fjaen** [MixedRealityToolkit/MixedRealityToolkit-Unity#657]
## Describe the bug

Hi,
I am experiencing problems when opening the MRTKDevTemplate project.
I have installed all the MRTK packages using the MRFTool (BTW, the org.mixedrealitytoolkit.data package was missing in the MRFTool and I had to install it from local disc using the corresponding json file of the cloned project).

After installing the packages and opening the MRTKDevTemplate project I get the following compilation errors

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/18660336/1af5d409-82bf-4434-be84-081957c656f4)

I have a W11 system, Unity 2021.3.21f1 and the following versions of MRTK3 packages:
org.mixedrealitytoolkit.accessibility: 1.0.1-pre.19
org.mixedrealitytoolkit.audio: 3.0.1
org.mixedrealitytoolkit.core: 3.1.1
org.mixedrealitytoolkit.data: 1.0.1-development
org.mixedrealitytoolkit.diagnostics: 3.0.1
org.mixedrealitytoolkit.extendedassets: 3.0.1
org.mixedrealitytoolkit.input: 3.1.0
org.mixedrealitytoolkit.spatialmanipulation: 3.1.0
org.mixedrealitytoolkit.standardassets: 3.0.1
org.mixedrealitytoolkit.tools: 3.0.1
org.mixedrealitytoolkit.uxcomponents: 3.1.1
org.mixedrealitytoolkit.uxcomponents.noncanvas: 3.1.1
org.mixedrealitytoolkit.uxcore: 3.1.1
org.mixedrealitytoolkit.windowsspeech: 3.0.1

Thanks for your help

## To reproduce

1. Install packages using MRFT
2. Open MRTKDevTemplate project in Unity 2021.3.21f1

**Comment by AMollis** [comment]
This looks like a regression caused by the Unity Asset Store support change.  I'll investigate

**Comment by AMollis** [comment]
@fjaen , why you are "installing" MRTK3 packages for "MRTKDevTemplate"?

The "MRTKDevTemplate" project in the MRTK3 repository already has references to the MRTK3 packages within the repository itself.  It does not rely on TGZ files.

Are you copying "MRTKDevTemplate" into your own project?

**Comment by AMollis** [comment]
@fjaen , I can't reproduce this problem.  The code that relies on `com.unity.asset-store-validation` is correctly getting disabled, if `com.unity.asset-store-validation` is not present.

If you want to use a copy of "MRTKDevTemplate" outside of the MRTK3 repository, please use the "release" version of "MRTKDevTemplate" from the latest release branch: https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/tree/releases/2024-01-12.   I think this will resolve you issue.

**Comment by fjaen** [comment]
Thank you very much @AMollis for your quick answer. I have now used the release version as you suggested, added the required packages with MRFTool and I still get compilation errors

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/18660336/992406ae-0ab6-4fd0-ba4b-3de8ab0e06a0)

The packages installed are 

org.mixedrealitytoolkit.accessibility: 1.0.1-pre.19
org.mixedrealitytoolkit.audio: 3.0.1
org.mixedrealitytoolkit.core: 3.0.0
org.mixedrealitytoolkit.data: 1.0.1-pre.19
org.mixedrealitytoolkit.diagnostics: 3.0.1
org.mixedrealitytoolkit.extendedassets: 3.0.1
org.mixedrealitytoolkit.input: 3.1.0
org.mixedrealitytoolkit.spatialmanipulation: 3.1.0
org.mixedrealitytoolkit.standardassets: 3.0.1
org.mixedrealitytoolkit.tools: 3.0.1
org.mixedrealitytoolkit.uxcomponents: 3.1.1
org.mixedrealitytoolkit.uxcomponents.noncanvas: 3.1.1
org.mixedrealitytoolkit.uxcore: 3.1.1
org.mixedrealitytoolkit.windowsspeech: 3.0.1

Thank you very much for your help

**Comment by fjaen** [comment]
Hi again @AMollis I narrowed it to just one compilation error

![imagen](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/18660336/919e728c-8b46-4147-9511-e3309a5fb0f8)

Thank you again
