### ISSUE TITLE
[MRTK3 FPS ISSUE] - Using MRTK3 + Unity3D (2021.3.15f1 LTS) + Quest 2

### ISSUE THREAD

**Issue by SattvariseTechonologiesPvtLtd** [MixedRealityToolkit/MixedRealityToolkit-Unity#665]
I'm having multiple GameObjects in my scene. When I attach the **ObjectManipulator** and **BoundsControl** scripts to GameObjects, the FPS drops below 10FPS in Unity(Play Mode) & Quest 2 also. 

Without those scripts, my FPS should be 60+.

**Please let me know your suggestions on this issue.**

![FPS Drop Issue](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/73810857/a48c01a1-5731-4ef3-8553-54e41acaae67)

**Comment by whebertML** [comment]
@SattvariseTechonologiesPvtLtd 

Your scene does seem to be fairly complex, having 2.1 million polygons, which could be affecting performance when things added to your scene.  How many objects are in your scene that you are adding ObjectManipulator and BoundsControl to where the issue arises?  Are you able to reproduce this issue in a simpler scene?  Please provide either a sample scene or reproduction steps to better investigate this issue.

**Comment by shaynie** [comment]
@SattvariseTechonologiesPvtLtd, closing this for now.  If you are able to repro in a simpler scene per @whebertML's comment, please re-open.
