### ISSUE TITLE
[BUG]MRTK3+Vuforia will meet some bugs, but mrtk2 do not meet these?

### ISSUE THREAD

**Issue by SangonomiyaSakunovi** [MixedRealityToolkit/MixedRealityToolkit-Unity#670]
## Describe the bug

I use the MRTK3 and open the Vuforia, then a lot bugs happened, I think both of them can`t work!

## To reproduce

1. Create a new project.
2. Import MRTK3
3. Improt Vuforia
4. The Error will see in Console

## Expected behavior

If nothing wrong, when i use MRTK simulator and MRTK XR Rig, in play mode, i can contorl the behavior.

## Your setup (please complete the following information)

- Unity Version [e.g. 2022.3.17f1]
- MRTK Version or Commit [e.g. v3.0] [e.g. [ba32bb2](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/commit/ba32bb2bcf6a90fafe4e8b21953ae387fa558a68)]

## Target platform (please complete the following information)

- HoloLens 2
- OpenXR

## Additional context

I am so confused that why MRTK2 can work with Vuforia, but MRTK3 can`t?

**Comment by AMollis** [comment]
@SangonomiyaSakunovi  can you please include the errors?  Are you sure this is not an issue with Vuforia's support with the Unity packages required by MRTK3?

**Comment by SangonomiyaSakunovi** [comment]
I had do some trys, maybe this issue is from Vuforia, or maybe because the Vuforia use Unity2023.3, possibly the MRTK3 need work at Unity2022?
For the above conclusion, I do a try: 
1. Create a 3D Core project in Unity2023.3.0.b10
2. Import MRTK3 with DeveloperTools
3. A error happened in Console.

And Beside this, I found a important API [ARAnchorManager.GetAnchor(TrackableId trackableId)], it can load the Anchor which store in XRAnchorStore. I do this step: 
TrackableId trackableId = _anchorStore.LoadAnchor(_anchorName);
ARAnchor anchor = _arAnchorManager.GetAnchor(trackableId);
_activeGameObject.transform.position = anchor.transform.position;
_activeGameObject.transform.rotation = anchor.transform.rotation;
With this four line, I can restore the anchor. This is so neccesary for our AR developer, but it`s so hard to find the Document, if you can, please update the Document. 
That may help other AR Developer, Thanks.

**Comment by AMollis** [comment]
@SangonomiyaSakunovi , the anchor APIs you mentioned are Unity APIs, please reach out to Unity for help.

@SangonomiyaSakunovi  can you please include a copy the error you are getting in the console window?
