### ISSUE TITLE
[BUG] CanvasElementRoundedRect starts flickering when placed more than a few hundred meters from world origin

### ISSUE THREAD

**Issue by halfpasttense** [MixedRealityToolkit/MixedRealityToolkit-Unity#675]
## Describe the bug
Any UI using CanvasElementRoundedRect starts flickering with what is probably z-fighting issues when it is place more than a few hundred meters from the world origin.

## To reproduce

Place any UI that has a CanvasElementRoundedRect on it more than a few hundred meters away from world origin then rotate or move the camera a bit to see the flicker. 

## Expected behavior

No flickering...

## Screenshots

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/40369329/d94fe6c5-5d0b-4eed-a7c7-1e4883a644d6)

## Your setup (please complete the following information)

- Unity Version [e.g. 2021.3.18f1]
- MRTK Version or Commit [e.g. v3.0.0-pre.16]

## Target platform (please complete the following information)

- OpenXR: Quest Pro

## Additional context

Users can teleport around freely in the world so it is possible to get far away from the world origin.

**Comment by AMollis** [comment]
Hi @halfpasttense

This looks like z-fighting.  Please change the depth of the backplate or the textboxes.   This is not directly related to the MRTK.  For help here, please visit our discuss forums.
