### ISSUE TITLE
[BUG]The self-built app deployment was successful, but it failed to run on the HoloLens 2.

### ISSUE THREAD

**Issue by keblicuey** [MixedRealityToolkit/MixedRealityToolkit-Unity#676]
Environment:

Unity 2022.3.15f1c1
MRTK3 or import packages，both tried+openXR
HoloLens 2
-vs2019
Problem:
After deploying the project to HL2 via VS, the self-created app appears in the HL2 application. However, upon opening, only a white box appears without displaying any models. I wonder how to solve it so that my scene can correctly present on the HL2. Thanks a lot.
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/81084513/8c4121be-e49a-4fce-adc2-393fb6d048da)

**Comment by AMollis** [comment]
Hi @keblicuey, please open a support ticket for HoloLens 2 at https://aka.ms/hldevsupport and someone from the Microsoft support team will assist you.
