### ISSUE TITLE
[BUG] OutlineExamples scene, center piece of tripod object does not outlines

### ISSUE THREAD

**Issue by ms-RistoRK** [MixedRealityToolkit/MixedRealityToolkit-Unity#692]
## Describe the bug

OutlineExamples scene, center piece of tripod object does not outlines

## To reproduce

1. Go to OutlineExamples scene
2. Select, point, gaze at tripod object center part
3. See error: The tripod object center piece does not outlines

## Expected behavior

The tripod object center piece should outline when pointed, gazed, selected.

## Your setup (please complete the following information)

- Unity Version [e.g. 2021.3.21f1]
- MRTK Version 3 or Commit https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/commit/d74d59f828d9eb6a169a29e6693ba32439d9c068

- HoloLens 2

## Additional context

This was detected as part of manual testing for next release signoff.

**Comment by AMollis** [comment]
This could be a graphic tool bug.   Pinging @Cameron-Micka

- https://github.com/microsoft/MixedReality-GraphicsTools-Unity
