### ISSUE TITLE
Holograms are not aligned with physical objects.

### ISSUE THREAD

**Issue by Hanning-Liu** [MixedRealityToolkit/MixedRealityToolkit-Unity#731]
## Describe the issue
> By default, mixed reality capture combines the right eye's holographic output with the photo/video (PV) camera. These two sources are combined using the focus point set by the currently running immersive app.
> 
> This means that holograms outside the focus plane won't align because of the physical distance between the PV camera and the right display.

The issue is clearly described in the link below and it also seems to provide a possible solution.
But it doesn't talk about the solution clearly.

## Feature area
Just like this:
> Render from the PV camera (opt-in)
>
> HoloLens 2 adds the ability for an immersive app to render from the PV camera while mixed reality capture is running. To ensure the app supports the additional render correctly, the app has to opt in to this functionality.
> 
> Render from the PV camera offers the following improvements over the default MRC experience:
> 
> Hologram alignment to your physical environment and hands for near interactions should be accurate at all distances. Avoid having an offset at distances other than the focus point as you might see in the default MRC.
> The right eye in the headset won't be compromised, as it won't be used to render the holograms for the MRC output.
>
>[Learn more about rendering from the PV camera (DirectX)](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/native/mixed-reality-capture-directx#render-from-the-pv-camera-opt-in).

## Existing doc link
https://learn.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/mixed-reality-capture-overview#render-from-the-pv-camera-opt-in

## Additional context
I also looked through the content in the DIrectX link. It provides a solution which is a little clearer. But it doesn't work either.
Just like this:

> There are three steps to enable rendering from the PV camera:
> 
> Enable the PhotoVideoCamera HolographicViewConfiguration
> Handle the additional HolographicCamera render
> Verify your shaders and code render correctly from this additional HolographicCamera
> Enable the PhotoVideoCamera HolographicViewConfiguration in DirectX
> To opt in to rendering from the PV Camera, an app simply enables the PhotoVideoCamera's [HolographicViewConfiguration](https://learn.microsoft.com/en-us/uwp/api/Windows.Graphics.Holographic.HolographicViewConfiguration):
> 
```
var display = Windows.Graphics.Holographic.HolographicDisplay.GetDefault();
var view = display.TryGetViewConfiguration(Windows.Graphics.Holographic.HolographicViewConfigurationKind.PhotoVideoCamera);
if (view != null)
{
   view.IsEnabled = true;
}
```
> Handle the additional HolographicCamera render in DirectX
> When the app has opt-in to render from the PV camera and mixed reality capture starts:
> 
> HolographicSpace's CameraAdded event will fire. This event can be deferred if the app can't handle the camera at this time.
> Once the event has completed with no outstanding deferrals, the HolographicCamera will appear in the next HolographicFrame's AddedCameras list.
> When mixed reality capture stops (or if the app disables the view configuration while mixed reality capture is running): the HolographicCamera will appear in the next HolographicFrame's RemovedCameras list and the HolographicSpace's CameraRemoved event will fire.
> 
> A [ViewConfiguration](https://learn.microsoft.com/en-us/uwp/api/windows.graphics.holographic.holographiccamera.viewconfiguration) property has been added to HolographicCamera to help identify the configuration a camera belongs to.
> 
> Verify shaders and code support additional cameras
> Run a mixed reality capture and check for unusual alignment, missing content, or performance issues. Update shaders and code as appropriate.
> 
> If there are certain scenes that can't support rendering to an additional camera, you can disable the PhotoVideoCamera's HolographicViewConfiguration.

Here is the error message I met:
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/42676581/650dd6d7-c5f8-471d-875c-45a68838391a)

**Comment by Hanning-Liu** [comment]
https://github.com/orgs/MixedRealityToolkit/discussions/563#discussion-5897688
Same issue was mentioned by a user half a year ago.

**Comment by AMollis** [comment]
Hi @Hanning-Liu , thank you for your issue.  Unfortunately this is not an MRTK3 bug.  The issue you've described is specific to HoloLens and related to the Hololen's Mixed Reality OpenXR Plugin for Unity.

By default, OpenXR on HoloLens enable 3rd person rendering.  This 3rd person rendering will make sure Hologram align correctly when viewed from the PV Camera.   Please check your Mixed Reality OpenXR plugin settings, verifying you haven't mistakenly disabled this functionality:

![Image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/36461279/8ba2535b-1e5d-4f0c-afcb-07807cfe0d77)

Note that the 3rd person renderer only works on device.  It doesn't not work in remoting scenarios.  Remote scenarios does not support 3rd person rendering.

If you are still having issues with Hololen's Mixed Reality OpenXR Plugin for Unity, please up a support ticket @ https://aka.ms/hldevsupport
