### ISSUE TITLE
[TRACKING] Enable TapToPlaceFollowsLeftHandRay Unity-test in org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/SolverTapToPlaceTests.cs for XRI3 migration

### ISSUE THREAD

**Issue by ms-RistoRK** [MixedRealityToolkit/MixedRealityToolkit-Unity#737]
Re-enable TapToPlaceFollowsLeftHandRay Unity-test in org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/SolverTapToPlaceTests.cs for XRI3 migration.

Note: Filing it as bug for easy reminder.

Related PR:

https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/716

Branch:

https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/tree/feature/XRI3

**Comment by AMollis** [comment]
@ms-RistoRK this needs to be fixed for XRI release

**Comment by ms-RistoRK** [comment]
Fix is in PR https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/760

**Comment by ms-RistoRK** [comment]
PR merged, closing this issue.
