### ISSUE TITLE
[TRACKING] Enable ScaleObjectTest Unity-test in org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/TransformViaInteractorTests.cs for XRI3 migration

### ISSUE THREAD

**Issue by ms-RistoRK** [MixedRealityToolkit/MixedRealityToolkit-Unity#738]
Re-enable ScaleObjectTest Unity-test in org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/TransformViaInteractorTests.cs for XRI3 migration.

Note: Filing it as bug for easy reminder.

Related PR:

https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/716

Branch:

https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/tree/feature/XRI3

**Comment by AMollis** [comment]
@ms-RistoRK this issue needs to be fixed before XRI3 support is released

**Comment by ms-RistoRK** [comment]
Fixed in feature/XRI3
