### ISSUE TITLE
[BUG] Last two asserts of FuzzyGazeInteractorTestsForControllerlessRig::EyeGazeWorksAsExpectedTest() succeed in Editor but fail in pipeline.

### ISSUE THREAD

**Issue by ms-RistoRK** [MixedRealityToolkit/MixedRealityToolkit-Unity#766]
## Describe the bug

Last two asserts of FuzzyGazeInteractorTestsForControllerlessRig::EyeGazeWorksAsExpectedTest() succeed in Editor but fail in pipeline.

## To reproduce

1. Uncomment assert lines.
2. Run locally in Editor
3. Run in pipeline
4. Compare results

## Expected behavior

Both pipeline and Editor test assert should throw the same result.

## Your setup (please complete the following information)

- Unity Version 2022.3.7f1
- MRTK XRI3 feature branch

## Target platform (please complete the following information)

- Build pipeline
- Editor

**Comment by AMollis** [comment]
should be fixed with

- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/862
