### ISSUE TITLE
[BUG] Quest Controllers does not invoke hover effects on Far Interaction

### ISSUE THREAD

**Issue by Ali-Can-Keskin** [MixedRealityToolkit/MixedRealityToolkit-Unity#768]
## Describe the bug

In Quest when using controllers (mainly tested with QUest 3), interactables that are below the middle line of users FOV (below half of users view) don't receive hover effects, so you don't really understand whether they are interactable or not

## To reproduce

Create a scene with interactables (you can have two of them,  one on high ground the other one near floor level) and try to hover on both of them. You will find it quite hard to invoke hover effects on the below one

## Expected behavior

If interactable has hover effects it should not matter which part of view it stands, it should be invoked if hovered.

- Unity Version 2021.3.32f1
- MRTK 2024-03-20 release

## Target platform (please complete the following information)

- Meat Quest Devices (2 & 3)
- OpenXR

**Comment by AMollis** [comment]
Unfortunately my fix only the fixes this in XRI3 Rig.   If the legacy rig is used, this behavior will still be broken.

**Comment by AMollis** [comment]
Bot the new and legacy rig have been updated in the Features/XRI3 branch.  

This feature branch will eventually be merged to main, you can follow progress here:

https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/645

**Comment by MaxPalmer-UH** [comment]
Thanks @AMollis
