### ISSUE TITLE
PressableButton's Inspector uses SerializedObject in OnSceneGUI

### ISSUE THREAD

**Issue by KUNGERMOoN** [MixedRealityToolkit/MixedRealityToolkit-Unity#782]
## Describe the bug

Selecting an object with Pressable Button component while having the Scene window open causes this error:
```
The serializedObject should not be used inside OnSceneGUI or OnPreviewGUI. Use the target property directly instead.
UnityEditor.Editor:get_serializedObject ()
MixedReality.Toolkit.Editor.PressableButtonEditor:OnSceneGUI () (at ./Library/PackageCache/org.mixedrealitytoolkit.uxcore@f549116c3343/Editor/Inspectors/PressableButton/PressableButtonInspector.cs:104)
(wrapper dynamic-method) object:lambda_method (System.Runtime.CompilerServices.Closure,UnityEditor.Editor)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```
This is being caused by: 
https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/blob/43aebd70e71bbe8b1ecc2df149469118d4ba63e1/org.mixedrealitytoolkit.uxcore/Editor/Inspectors/PressableButton/PressableButtonInspector.cs#L104

## To reproduce

1. Clone: https://github.com/KUNGERMOoN/MRTK-Tutorial
2. Make sure you have both the Scene and Inspector windows open
3. Open Assets/Scenes/Main
4. Select RoverExplorer/Buttons/Hints

## Expected behavior
No errors

## Your setup

- Unity 2022.3.16f1
- MRTK3 packages:
  org.mixedrealitytoolkit.accessibility: 1.0.3-pre.20
  org.mixedrealitytoolkit.audio: 3.0.3
  org.mixedrealitytoolkit.core: 3.2.1
  org.mixedrealitytoolkit.diagnostics: 3.0.2
  org.mixedrealitytoolkit.extendedassets: 3.0.2
  org.mixedrealitytoolkit.input: 3.2.1
  org.mixedrealitytoolkit.spatialmanipulation: 3.3.0
  org.mixedrealitytoolkit.standardassets: 3.2.0
  org.mixedrealitytoolkit.tools: 3.0.3
  org.mixedrealitytoolkit.uxcomponents: 3.3.0
  org.mixedrealitytoolkit.uxcomponents.noncanvas: 3.1.3
  org.mixedrealitytoolkit.uxcore: 3.2.1
  org.mixedrealitytoolkit.windowsspeech: 3.0.3

## Target platform

- HoloLens 2

## Additional context

Edit:
Probably related to #772

**Comment by anonymous2585** [comment]
I got the same issue:
1. Open the scene `CanvasExample` of the MRTKDevTemplate project
2. Select one of the PressableButton in the scene view
3. See the error

I found that removing the [CanEditMultipleObjects] attribute fixed this issue. It was introduced in PR #698

**Comment by Therobopy** [comment]
Hello, 

I was setting up a basic UI in Unity for an application to deploy on HoloLens 2 using the MRTK 3 UI components and I still get the same error as explained above. Commenting the attribute [CanEditMultipleObjects] also works for me to fix the issue, but I'm not sure it's the right way.
