### ISSUE TITLE
[BUG] Broken asset in HandInteractionExamples scene in MRTK3/main branch

### ISSUE THREAD

**Issue by ms-RistoRK** [MixedRealityToolkit/MixedRealityToolkit-Unity#848]
## Describe the bug

The following asset is broken in HandInteractionExamples scene HandInteractionExamples\MixedRealitySceneContent\Touch Interaction\MRTK_Logo as in:

![image](https://github.com/user-attachments/assets/ea6e5022-fd90-4c0e-9049-5b1727105758)

## To reproduce

1. Clone MRTK3/main branch
2. Open in Editor HandInteractionExamples scene
3. Expand scene hierarchy until reaching HandInteractionExamples\MixedRealitySceneContent\Touch Interaction\MRTK_Logo
4. See error that MRTK_Logo is missing

![image](https://github.com/user-attachments/assets/f5328957-5547-4694-be4b-0b3595dcc512)

## Expected behavior

When opening HandInteractionExamples scene the MRTK_Logo under Touch Interaction should not be broken.

## Screenshots

![image](https://github.com/user-attachments/assets/a59665c9-5c4b-4f96-a2ec-cbad13cef913)

## Your setup (please complete the following information)

- Unity Version [e.g. 2021.3.21f1]
- MRTK Version or Commit 875b35250f107701aaa0217648e522a4cf8d1b13
- MRTK3/main branch

## Target platform (please complete the following information)

- HoloLens 2

**Comment by whebertML** [comment]
@ms-RistoRK , I'm not seeing that missing prefab reference at all, in a clean & freshly synced latest `feature/XRI3` branch.

![image](https://github.com/user-attachments/assets/a0bdd99b-1b85-4696-b355-3e3e06fecaca)

Wonder if you need to delete Library folder and re-open the project, and if you'd still see that.

**Comment by ms-RistoRK** [comment]
Update: This is not a repo issue. The problem was that my git-lfs stopped working and after re-installing it all assets are now properly decoded.  Closing this issue.
