### ISSUE TITLE
[BUG] MRTK Graphics tools 0.7.1 FlyCamera Prefabs Missing script

### ISSUE THREAD

**Issue by yty** [MixedRealityToolkit/MixedRealityToolkit-Unity#887]
## Describe the bug

Missing script file...
 
## Screenshots
![q2](https://github.com/user-attachments/assets/c365ee5e-e810-4bd4-94eb-97769b358570)

## Your setup 

- Unity 2022.3.35f1
- MRTK Graphics tools 0.7.1

## Target platform

- HoloLens 2

**Comment by shaynie** [comment]
@yty The graphics tools project maintains their own bug board.  Please create a bug here:  https://github.com/microsoft/MixedReality-GraphicsTools-Unity/issues
