### ISSUE TITLE
[XRI3] [BUG] Rigged hand mesh visualizer gets stuck "on" when using a hand interaction profile

### ISSUE THREAD

**Issue by keveleigh** [MixedRealityToolkit/MixedRealityToolkit-Unity#890]
## Describe the bug

When using a hand interaction profile, the rigged hand mesh visualizer's select action reader logic causes the selection outline highlighting to be stuck on after an initial pinch.

## To reproduce

1. Enable the Hand Interaction Profile in the OpenXR settings (may also repro with the Microsoft Hand Interaction Profile)
2. Ensure `pointerActivateValue` is present in your select action mappings
    1. ![image](https://github.com/user-attachments/assets/3cf1fa67-502c-4f99-a8d6-f620c6c4dc93)
2. Run an MRTK examples with the rigged hand mesh (like HandInteractionExamples)
3. Pinch!

## Expected behavior

On unpinch, the outline highlighting will return to the default, unhighlighted state

## Screenshots

![image](https://github.com/user-attachments/assets/ea69e3f2-bbe9-45af-adb5-c57b51f00415)

**Comment by shaynie** [comment]
Fixed with #891
