### ISSUE TITLE
[FEATURE REQUEST] Locally persistent anchor requests (such as API for WorldAnchorStore in Unity 2019)

### ISSUE THREAD

**Issue by zhangtianhong-1998** [MixedRealityToolkit/MixedRealityToolkit-Unity#899]
## Describe the problem
Regarding locally persistent anchor requests, I noticed that older versions of Unity included WorldAnchorStore to provide a solution for locally persisting anchors.  However, this 2019 version of Unity has been dropped, and MRTK3 does not support older versions of Unity.  In practice, due to application requirements, some scenarios are that the public network is disconnected or the public network is not allowed to access.  

## Describe the solution you'd like

This created a big obstacle for us in MRTK3 English, and I asked the development team to reconsider the feasibility of locally persistence anchor requests for MRTK3 supplement

**Comment by anonymous2585** [comment]
The package [Mixed Reality OpenXR Plugin](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/releases) provide all what you need to save and load anchors on Hololens 2. We use it to save anchors with MRTK 3, and it works great with Unity 2023 and Unity 6 Preview.

Class to use is `XRAnchorStore` with methods:
- `XRAnchorStore.LoadAnchorStoreAsync(XRAnchorSubsystem anchorSubsystem)` to get a reference to the `xrAnchorStore` instance
- `xrAnchorStore.TryPersistAnchor(TrackableId trackableId, string name)` to save an anchor with a name
- `xrAnchorStore.UnpersistAnchor(string name)` to clear a saved anchor from its name
- `xrAnchorStore.LoadAnchor(string name)` to load one anchor by name and get it's `TrackableId`. You will get the anchor object at the next frame in your `ARAnchorManager` with the event `OnAnchorChanged(ARAnchorsChangedEventArgs eventArgs)`
- The list `xrAnchorStore.PersistedAnchorNames` to get all saved anchors name (usefull to iterate on it and load them)

**Comment by shaynie** [comment]
@zhangtianhong-1998, please see the above comment from @anonymous2585 on how to use this on HL2.
