### ISSUE TITLE
[BUG] When creating a new MRTK3 project, if you don’t create an MRTK3 profile, you will generate two Project Validation warnings:

### ISSUE THREAD

**Issue by AMollis** [MixedRealityToolkit/MixedRealityToolkit-Unity#906]
## Describe the bug

When creating a new MRTK3 project, if you don’t create an MRTK3 profile, you will generate two Project Validation warnings:

“[MRTK3] MRTK3 profile may need to be assigned for the Standalone build target”.

“[MRTK3] MRTK3 profile may need to be assigned for the Metro build target”. 

When you click on either question mark next to the Fix button, you are taken to a Microsoft learn page that is not found and generates a 404. See attached image.

## To reproduce

1. Create a new Unity 3D Core project using the editor of choice.
2.  Switch to the UWP platform on the build tab, save and exit the project.
3. Run the Mixed Reality Feature Tool for Unity and add the following “standard” MRTK3 packages to the project. "com.microsoft.mixedreality.openxr-1.11.1", "com.microsoft.mrtk.graphicstools.unity-0.7.1", "com.microsoft.spatialaudio.spatializer.unity-2.0.55", "org.mixedrealitytoolkit.core-3.2.1", "org.mixedrealitytoolkit.input-3.2.1", "org.mixedrealitytoolkit.spatialmanipulation-3.3.0", "org.mixedrealitytoolkit.standardassets-3.2.0", "org.mixedrealitytoolkit.uxcomponents-3.3.0", "org.mixedrealitytoolkit.uxcomponents.noncanvas-3.1.3", "org.mixedrealitytoolkit.uxcore-3.2.1".
4.  After adding the MRTK3 packages and exiting the tool, reopen your Unity project. As you haven’t yet set the default MRTK profile under Project Settings → MRTK3, you should get the two warnings listed above under Project Settings → XR Plug-in Management → Project Validation.
5. Click on the question mark icons for either warning, found next to the Fix button.

## Resulting behavior

Your default browser opens to “https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/mrtk-unity/mrtk3-overview/getting-started/setting-up/setup-new-project.md#4-configure-mrtk-profile-after-import“ which generates [404 - Content Not Found | Microsoft Learn](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/mrtk-unity/mrtk3-overview/getting-started/setting-up/setup-new-project.md#4-configure-mrtk-profile-after-import). See attached screenshot.

## Expected behavior

Creator is linked to an existing Microsoft Learn website that shows how to configure an MRTK3 profile for the project.

## Screenshots

![image](https://github.com/user-attachments/assets/7a8942ad-d934-4478-9629-d1dd8f91804a)

## Your setup (please complete the following information)

- Unity Version [e.g. 2021.3.21f1]
- MRTK Version or Commit [e.g. v3.0] [e.g. [ba32bb2](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/commit/ba32bb2bcf6a90fafe4e8b21953ae387fa558a68)]

## Target platform (please complete the following information)

- HoloLens 2
- Magic Leap
- OpenXR

**Comment by MaxPalmer-UH** [comment]
I've just checked this link on my system and it's working. Perhaps the external learn site has been fixed/updated?
https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/getting-started/setting-up/setup-new-project#4-configure-mrtk-profile-after-import

**Comment by MaxPalmer-UH** [comment]
Link no longer appears to be broken.
