### ISSUE TITLE
[BUG] Clipping primitives (MaterialInstance) cause material properties to get lost during copies

### ISSUE THREAD

**Issue by NoTuxNoBux** [MixedRealityToolkit/MixedRealityToolkit-Unity#916]
## Describe the bug

`MaterialInstance.Instance` makes a copy of the source material, but it does not copy any properties that were set. This can break material shaders.

## To reproduce

1. Create a `Renderer` with a `Material` configured that has a shader that uses specific properties (e.g. an integer property should do) to change appearance visually.
2. Assign a value to the property using e.g. `yourRenderer.sharedMaterial.SetInteger("_Foo", 5);`.
3. Add a `ClippingPrimitive` to the scene.
4. Attach the created renderer to the clipping primitive.
5. Notice that the appearance is incorrect because the material instance copied by the clipping primitive (`MaterialInstance`) does not get `_Foo` set.

## Expected behavior

When copying materials, properties are also copied, e.g. adding `output.CopyPropertiesFromMaterial(source);` underneath `Material output = new Material(source);` in `MaterialInstance.Instance` seems to fix the issue for me.

## Your setup (please complete the following information)

- Unity Version [e.g. 2021.3.21f1]: 6000.0.11f1
- MRTK Version or Commit [e.g. v3.0] [e.g. [ba32bb2](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/commit/ba32bb2bcf6a90fafe4e8b21953ae387fa558a68)]: 3.2.0

## Target platform (please complete the following information)

- Meta Quest 3
- Oculus XR as OpenXR back end with Meta SDK

**Comment by Cameron-Micka** [comment]
Thanks @NoTuxNoBux! Linking here so this doesn't get lost: https://github.com/microsoft/MixedReality-GraphicsTools-Unity/issues/221

**Comment by shaynie** [comment]
MRGT has this bug
