### ISSUE TITLE
[BUG] MicrosoftOpenXRPlugin.dll missing for linux editor 

### ISSUE THREAD

**Issue by TheXRMonk** [MixedRealityToolkit/MixedRealityToolkit-Unity#927]
## Describe the bug

There's no MicrosoftOpenXRPlugin.dll for Unity linux editor - we can't build or run tests in our linux-based CI/CD pipeline.

## To reproduce

Just open up a unity project with MRT3 on linux.

## Expected behavior

No errors.

## Screenshots
N/A

## Your setup (please complete the following information)

- Unity Version 6000.0.5f1
- Using newest version of MicrosoftOpenXRPlugin

## Target platform (please complete the following information)

- Linux Editor

## Additional context
N/A

**Comment by AMollis** [comment]
Are there OpenXR extensions that you require from MicrosoftOpenXRPlugin?  If not, the recommended solution would be to remove MicrosoftOpenXRPlugin, as this is not a hard requirement.

@TheXRMonk what platform are you targeting?   Android, Stand Alone, UWP, ect?

**Comment by TheXRMonk** [comment]
We're targeting Android (Quest), but it seems like just removing the package creates a lot of errors in rest of the MRTK packages.

**Comment by TheXRMonk** [comment]
We're getting this warning:
![image](https://github.com/user-attachments/assets/c6deb5ad-f2d9-4738-aa19-3e2a0244dff8)
With this setup:
![image](https://github.com/user-attachments/assets/776969e5-d6e9-4161-9070-335192f922ae)

But the MixedRealityFeatureTool does not contain a package named _mixedreality.toolkit.input.openxrhandssubsystem_

**Comment by TheXRMonk** [comment]
Just upgrade all packages - still getting the warnings above. 
It seems like it's still dependent on MS OpenXR, when reading these script defines _MROPENXR_PRESENT:_
![image](https://github.com/user-attachments/assets/e3816d6b-c5e1-48b9-9131-9494e98738b6)

**Comment by TheXRMonk** [comment]
Alright, I'm stupid - of course, I need to activate it in the MRTK Profile... Sorry for the inconvenience!
