### ISSUE TITLE
[BUG] ObjectManipulator rotation is inverted in some cases with constraint on two axes

### ISSUE THREAD

**Issue by NoTuxNoBux** [MixedRealityToolkit/MixedRealityToolkit-Unity#952]
## Describe the bug

This is basically https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8947 from the MRTK2, but for the MRTK3 - the original issue was closed because of the MRTK2 being retired, but I also seem to be experiencing a similar issue in the MRTK3 with a similar setup.

## To reproduce

See also the original issue's reproduction steps, my setup is very similar:

1. Have a 3D object such as a cube with the necessary collider on it.
2. Set an `ObjectManipulator` on it.
3. Configure an `AxisRotationConstraint` to restrict the X and Z axes (so you can only rotate from 'left to right' or over the Y axis). Keep `Hand Type` and `Proximity Type` on `Everything`, don't enable `Use Local Space For Constraint`.
4. When using a single hand to move the object left and right in play mode, moving your hand left after grabbing rotates the object right and the other way around.

In my case I have an object that was rotated 180º so I first suspected that was causing it, but it wasn't.

## Expected behavior

The inverse happens; moving hand left rotates the object left as well.

## Your setup (please complete the following information)

- Unity Version: 6000.0.11f1
- MRTK Version or Commit: 3.2.0.

## Target platform (please complete the following information)

- Meta Quest 3
- Meta XR

## Additional context

I was able to create my own `RotateLogic` and attach it to the `ObjectManipulator` to fix the issue:

```cs
public sealed class ObjectManipulatorReversedRotateLogic : ManipulationLogic<Quaternion>
{
    private Vector3 startHandlebar;
    private Quaternion startInputRotation;
    private Quaternion startRotation;

    /// <inheritdoc />
    public override void Setup(List<UnityEngine.XR.Interaction.Toolkit.Interactors.IXRSelectInteractor> interactors, UnityEngine.XR.Interaction.Toolkit.Interactables.IXRSelectInteractable interactable, MixedRealityTransform currentTarget)
    {
        base.Setup(interactors, interactable, currentTarget);

        if (NumInteractors >= 2)
        {
            startHandlebar = GetHandlebarDirection(interactors, interactable);
        }

        startInputRotation = interactors[0].GetAttachTransform(interactable).rotation;
        startRotation = currentTarget.Rotation;
    }

    /// <inheritdoc />
    public override Quaternion Update(
        List<UnityEngine.XR.Interaction.Toolkit.Interactors.IXRSelectInteractor> interactors,
        UnityEngine.XR.Interaction.Toolkit.Interactables.IXRSelectInteractable interactable,
        MixedRealityTransform currentTarget,
        bool centeredAnchor)
    {
        base.Update(interactors, interactable, currentTarget, centeredAnchor);

        if (NumInteractors == 1)
        {
            // NOTE: Only this line changed as opposed to the original MRTK RotateLogic.
            return Quaternion.Inverse(interactors[0].GetAttachTransform(interactable).rotation) * startInputRotation * startRotation;
        }
        else
        {
            // TODO: This gimbal locks if you hold an object with two hands and then rotate your body a full 180 degrees.
            return Quaternion.FromToRotation(startHandlebar, GetHandlebarDirection(interactors, interactable)) * startRotation;
        }
    }

    private static Vector3 GetHandlebarDirection(List<UnityEngine.XR.Interaction.Toolkit.Interactors.IXRSelectInteractor> interactors, UnityEngine.XR.Interaction.Toolkit.Interactables.IXRSelectInteractable interactable)
    {
        Debug.Assert(interactors.Count >= 2, $"GetHandlebarDirection called with less than 2 interactors ({interactors.Count}).");
        return interactors[1].GetAttachTransform(interactable).position - interactors[0].GetAttachTransform(interactable).position;
    }
}
```

**Comment by AMollis** [comment]
@whebertML can you please try to reproduce this issue?  Leaving "triage" flag while @whebertML investigates

**Comment by whebertML** [comment]
@NoTuxNoBux 

I tried reproducing this issue in both Editor play mode and on a device, no luck so far.

I tried adding a RotationAxisConstraint with restriction in X,Z axis on one of the coffee cups in the HandInteractionExamples scene, as well as creating a new Cube, adding an ObjectManipulator and then adding RotationAxisConstraint, all from scratch as in your repro steps - they both seemed to rotate properly when grabbed (rotate right when rotating my hand right, left when rotation left, etc.).

Is there perhaps a step or configuration I'm missing?  If you had a video screen capture, or even a git branch somewhere with your scene setup I could test, that might help.

**Comment by NoTuxNoBux** [comment]
@whebertML Thanks for the response. I have a project where this reproduces; I will try to extract the problematic part of it and get back with a reproducible example.

**Comment by NoTuxNoBux** [comment]
@whebertML I added an example [here](https://github.com/NoTuxNoBux/UnityMRTKStrangeObjectManipulatorBugCase).

How to reproduce:

1. Build/run for the Quest 2 or 3.
2. Notice how using the far ray from your hand to move it right moves the circle left and left moves right.

Near interaction has the same problem.

In the editor I can't test this with the simulation since far rays don't appear to be able to do anything and near interaction results in a momentary interaction and then stops.

**Comment by whebertML** [comment]
@NoTuxNoBux 

Thanks for the example project, that helps clear up the issue I believe.  Your object, the WindRoseSmooth ring, makes your intent more clear - that of grabbing the ring and manipulating the ring and content as if like on a carousel?

So yes, it does indeed appear the ring rotates opposite of what you'd expect.  Like when grabbing the ring with a far ray interactor and rotating the controller to the right so the grab point would move to the right, the expectation would be the ring would follow from the grab point and rotate that way, but instead the oppose is happening and it rotates to the left.

This is, however, how the standard RotateLogic is designed and intended - which is to follow the relative rotation of the interactor's attach point from the moment of selection.  In the case with the far ray interactor, for example, the attach point continues to follow the direction the far ray is pointing at the end of the ray, and so the object manipulator's RotateLogic attempts to match that attach point rotation.

How this behaves normally is more clear if there isn't the rotate only constraint to visualize what is going on.  So to better illustrate, I created a simple example with your ring and attached the familiar Lander object to it (Lander from the MRTKDevTemplate project).  I created 2 copies of this setup, one with the rotate constraint, and one allowing free movement without constraint that makes the rotation more clear.  But in both cases, the RotateLogic is the same and you should be able to see that it is just using the ray interactor's attach transform (indicated by the Axis inside the red sphere at the end of the ray) to rotate the object.  And you should see both objects have basically matching rotation, one just constrained to Y axis only, the other free.

![Image](https://github.com/user-attachments/assets/bc4da686-2df7-40fb-bd77-45f1c6c50cd1)

So I don't believe this indicates there is any issue with the standard RotateLogic.  It was just intended for grabbing the whole object and rotating it relative to any changes in the interactor's attach transform, which works for the majority of use cases.  The are likely several good ways to go about implementing what you want to do, but probably the best I can think of is to do exactly what you did - just create a custom rotate logic to do what you need for your special circumstance and assign that to the object.

**Comment by NoTuxNoBux** [comment]
@whebertML Thanks for the clarification! The GIF visually explains well what is happening in the background. The current behaviour now makes more sense to me.

I'll close this since it's indeed intended behaviour.

**Comment by whebertML** [comment]
Moving to closed as not planned so it won't show up in our "Ready for Release" list.
