### ISSUE TITLE
[BUG] Typo in InteractorModeManager.cs destroyed interactor group cleanup.

### ISSUE THREAD

**Issue by whebertML** [MixedRealityToolkit/MixedRealityToolkit-Unity#963]
## Describe the bug

In InteractorModeManager.Update(), there is a feature/XRI3 migration typo bug where destroyed interactor groups are not being removed from the interactorGroupMappings as they should, but incorrectly removed from their own collection, causing spamming of the following error:

InvalidOperationException: Collection was modified; enumeration operation may not execute.

## To reproduce

1. Open a scene within the feature/XRI3 branch
2. Click on MRTK Interaction Manager object within the rig
3. Add a Interactor Group Mapping entry with null, "None (Game Object)" key - this entry will be removed by the destroyed entry logic within the Update loop.
4. Run the scene in Editor play mode.
5. Notice error spam

## Expected behavior

Correct handling of destroyed/non-existent interactor groups.

## Your setup (please complete the following information)

- Unity Version [e.g. 2022.3.21f1]
- MRTK Version or Commit [feature/XRI3 branch]

## Target platform (please complete the following information)

- HoloLens 2
- Magic Leap
- OpenXR

**Comment by whebertML** [comment]
Fix in #964

**Comment by keveleigh** [comment]
Fixed via #964
